syntax = "proto3";

package accountcacher;

service AccountMgr {
  rpc BanPlayer(BanPlayerRequest) returns (BanPlayerResponse);
  rpc ModifyAccess(ModifyAccessRequest) returns (ModifyAccessResponse);
  rpc SanctionPlayer(SanctionPlayerRequest) returns (SanctionPlayerResponse);
}

message BanPlayerRequest {
  string username = 1;
  string reason = 2;
  int64 ban_expiry = 3;
}

message BanPlayerResponse {
  bool success = 1;
  string error_message = 2;
}

message ModifyAccessRequest {
  string username = 1;
  int32 gm_level = 2;
  int32 core_level = 3;
}

message ModifyAccessResponse {
  bool success = 1;
  string error_message = 2;
}

message SanctionPlayerRequest {
  string username = 1;
  string sanction_type = 2;
  string details = 3;
  int64 expiry = 4;
}

message SanctionPlayerResponse {
  bool success = 1;
  string error_message = 2;
}