-- Various item matching and updates

UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Elixir of Allaying', `SpellId` = '7878' WHERE (`Entry` = '190477');
DELETE FROM `war_world`.`item_infos` WHERE (`Entry` = '3000001');
UPDATE `war_world`.`item_infos` SET `SpellId` = '7206' WHERE (`Entry` = '157882');
DELETE FROM `war_world`.`item_infos` WHERE (`Entry` = '3000006');
UPDATE `war_world`.`item_infos` SET `SpellId` = '7211' WHERE (`Entry` = '157887');
DELETE FROM `war_world`.`item_infos` WHERE (`Entry` = '3000011');
UPDATE `war_world`.`item_infos` SET `SpellId` = '7216' WHERE (`Entry` = '157892');
DELETE FROM `war_world`.`item_infos` WHERE (`Entry` = '3000016');
UPDATE `war_world`.`item_infos` SET `SpellId` = '7221' WHERE (`Entry` = '157897');
UPDATE `war_world`.`abilities` SET `Entry` = '7206', `Cooldown` = '120' WHERE (`Entry` = '7875');
UPDATE `war_world`.`abilities` SET `Cooldown` = '120' WHERE (`Entry` = '7221');
UPDATE `war_world`.`abilities` SET `Cooldown` = '120' WHERE (`Entry` = '7880');
UPDATE `war_world`.`abilities` SET `Cooldown` = '120' WHERE (`Entry` = '7885');
INSERT INTO `war_world`.`abilities` (`Entry`, `Name`, `Cooldown`, `EffectID`, `Specline`, `IgnoreGlobalCooldown`) VALUES ('7211', 'Brief Elixir of Balming', '120', '2751', 'Item', '1');
INSERT INTO `war_world`.`abilities` (`Entry`, `Name`, `Cooldown`, `EffectID`, `Specline`, `IgnoreGlobalCooldown`) VALUES ('7216', 'Brief Elixir of Respite', '120', '2751', 'Item', '1');
INSERT INTO `war_world`.`abilities` (`Entry`, `Name`, `Cooldown`, `EffectID`, `Specline`, `IgnoreGlobalCooldown`) VALUES ('7226', 'Brief Elixir of Healing', '120', '2751', 'Item', '1');
INSERT INTO `war_world`.`abilities` (`Entry`, `Name`, `Cooldown`, `EffectID`, `IgnoreGlobalCooldown`) VALUES ('7231', 'Brief Elixir of Aid', '120', '2751', '1');
INSERT INTO `war_world`.`abilities` (`Entry`, `Name`, `Cooldown`, `EffectID`, `IgnoreGlobalCooldown`) VALUES ('7236', 'Brief Elixir of Restoration', '120', '2751', '1');
INSERT INTO `war_world`.`abilities` (`Entry`, `Name`, `Cooldown`, `EffectID`, `IgnoreGlobalCooldown`) VALUES ('7246', 'Brief Elixir of Remedy', '120', '2751', '1');
INSERT INTO `war_world`.`abilities` (`Entry`, `Name`, `Cooldown`, `EffectID`, `IgnoreGlobalCooldown`) VALUES ('7251', 'Brief Elixir of Recovery', '120', '2751', '1');
INSERT INTO `war_world`.`abilities` (`Entry`, `Name`, `Cooldown`, `EffectID`, `IgnoreGlobalCooldown`) VALUES ('7847', 'Weak Brief Elixir of Allaying', '120', '2751', '1');
INSERT INTO `war_world`.`abilities` (`Entry`, `Name`, `Cooldown`, `EffectID`, `IgnoreGlobalCooldown`) VALUES ('7875', 'Brief Elixir of Allaying', '120', '2751', '1');
INSERT INTO `war_world`.`abilities` (`Entry`, `Name`, `Cooldown`, `EffectID`, `IgnoreGlobalCooldown`) VALUES ('7241', 'Brief Elixir of Mending', '120', '2751', '1');
INSERT INTO `war_world`.`abilities` (`Entry`, `Name`, `Cooldown`, `EffectID`, `IgnoreGlobalCooldown`) VALUES ('7256', 'Brief Elixir of Soothing', '120', '2751', '1');
UPDATE `war_world`.`item_infos` SET `SpellId` = '7231' WHERE (`Entry` = '157907');
INSERT INTO `war_world`.`item_infos` (`Entry`, `Name`, `Description`, `Type`, `Race`, `ModelId`, `SlotId`, `Rarity`, `Career`, `Skills`, `Bind`, `Armor`, `SpellId`, `Dps`, `Speed`, `MinRank`, `MinRenown`, `StartQuest`, `Stats`, `SellPrice`, `TalismanSlots`, `MaxStack`, `ObjectLevel`, `UniqueEquiped`, `Unk27`, `TwoHanded`, `ItemSet`, `TokUnlock`, `TokUnlock2`, `IsSiege`) VALUES ('157004', 'Brief Elixir of Allaying', 'Gradually restores {COM_0_VAL0_TOD_HEALTH} over {COM_0_DURA_SECONDS}.', '31', '0', '714', '0', '2', '0', '0', '0', '0', '7875', '0', '0', '40', '0', '0', '0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;', '30', '0', '20', '44', '0', '0 1 0 1 3 2 0 0 0 0 0 0 0 0 0 0 0 0 0 5 0 0 0 0 0 0 0', '0', '0', '0', '0', '0');
UPDATE `war_world`.`item_infos` SET `Description` = 'Heals for {COM_0_VAL0} every {COM_0_FREQ_SECONDS}, for {COM_0_DURA_SECONDS}.' WHERE (`Entry` = '157882');
UPDATE `war_world`.`item_infos` SET `SpellId` = '7226' WHERE (`Entry` = '157902');
UPDATE `war_world`.`item_infos` SET `Description` = 'Heals for {COM_0_VAL0} every {COM_0_FREQ_SECONDS}, for {COM_0_DURA_SECONDS}.', `SpellId` = '7241' WHERE (`Entry` = '157917');
INSERT INTO `war_world`.`item_infos` (`Entry`, `Name`, `Description`, `Type`, `Race`, `ModelId`, `SlotId`, `Rarity`, `Career`, `Skills`, `Bind`, `Armor`, `SpellId`, `Dps`, `Speed`, `MinRank`, `MinRenown`, `StartQuest`, `Stats`, `SellPrice`, `TalismanSlots`, `MaxStack`, `ObjectLevel`, `UniqueEquiped`, `Unk27`, `TwoHanded`, `ItemSet`, `TokUnlock`, `TokUnlock2`, `IsSiege`) VALUES ('157005', 'Brief Elixir of Mending', 'Gradually restores {COM_0_VAL0_TOD_HEALTH} over {COM_0_DURA_SECONDS}.', '31', '0', '721', '0', '2', '0', '0', '0', '0', '7880', '0', '0', '32', '0', '0', '0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;', '30', '0', '20', '32', '0', '0 1 0 1 3 2 0 0 0 0 0 0 0 0 0 0 0 0 0 5 0 0 0 0 0 0 0', '0', '0', '0', '0', '0');
UPDATE `war_world`.`item_infos` SET `Description` = 'Heals for {COM_0_VAL0} every {COM_0_FREQ_SECONDS}, for {COM_0_DURA_SECONDS}.', `SpellId` = '7251' WHERE (`Entry` = '157927');
INSERT INTO `war_world`.`item_infos` (`Entry`, `Name`, `Description`, `Type`, `ModelId`, `SlotId`, `Rarity`, `Career`, `Skills`, `Bind`, `Armor`, `SpellId`, `Dps`, `Speed`, `MinRank`, `MinRenown`, `StartQuest`, `Stats`, `SellPrice`, `TalismanSlots`, `MaxStack`, `ObjectLevel`, `UniqueEquiped`, `Unk27`, `TwoHanded`, `ItemSet`, `TokUnlock`, `TokUnlock2`, `IsSiege`) VALUES ('157006', 'Brief Elixir of Recovery', 'Gradually restores {COM_0_VAL0_TOD_HEALTH} over {COM_0_DURA_SECONDS}.', '31', '723', '0', '2', '0', '0', '0', '0', '7885', '0', '0', '38', '0', '0', '0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;', '30', '0', '20', '36', '0', '0 1 0 1 3 2 0 0 0 0 0 0 0 0 0 0 0 0 0 5 0 0 0 0 0 0 0', '0', '0', '0', '0', '0');
UPDATE `war_world`.`item_infos` SET `SpellId` = '7246' WHERE (`Entry` = '157922');
UPDATE `war_world`.`item_infos` SET `SpellId` = '7236' WHERE (`Entry` = '157912');
UPDATE `war_world`.`item_infos` SET `SpellId` = '7256' WHERE (`Entry` = '157932');
DELETE FROM `war_world`.`item_infos` WHERE (`Entry` = '3000004');
UPDATE `war_world`.`item_infos` SET `Description` = 'Heals for 30 health every 2 seconds, for 12 seconds.', `SpellId` = '7209' WHERE (`Entry` = '157885');
UPDATE `war_world`.`item_infos` SET `Description` = 'Gradually restores 3600 health over 24 seconds.' WHERE (`Entry` = '190477');
INSERT INTO `war_world`.`ability_damage_heals` (`Entry`, `Index`, `Name`, `MinDamage`, `MaxDamage`, `DamageType`, `ParentCommandID`, `ParentCommandSequence`, `HatredScale`, `HealHatredScale`) VALUES ('7209', '1', 'Lasting Elixir of Allaying', '180', '180', 'RawHealing', '0', '0', '1', '1');
UPDATE `war_world`.`ability_damage_heals` SET `MinDamage` = '3600' WHERE (`Entry` = '7878') and (`Index` = '1') and (`ParentCommandID` = '0') and (`ParentCommandSequence` = '0');
INSERT INTO `war_world`.`ability_commands` (`Entry`, `AbilityName`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `Target`) VALUES ('7209', 'Lasting Elixir of Allaying', '0', '0', 'InvokeBuff', '7209', 'Caster');
