<Project>
  <PropertyGroup>
    <BaseOutputPath>$(MSBuildThisFileDirectory)build/bin/</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)build/obj/</BaseIntermediateOutputPath>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifiers>win</RuntimeIdentifiers>
  </PropertyGroup>
</Project>
