UPDATE `war_world`.`quests` SET `Description` = 'Sigmar be praised, the reinforcements have arrived at last! Not a moment too soon either, looks to me as if the Raven Host is gearing up for another assault. We\'ve got things pretty well contained here at the moment, but beyond the city... well, you\'ll see. Anyway, that\'s neither here nor there. You didn\'t come here to talk, you came to fight. Go see the Martial Marshal just over yonder in the War Quarter. He\'ll get you kitted out.', `Particular` = 'Go to the War Quarter in Altdorf. Talk to the Martial Marshal for your battle gear' WHERE (`Entry` = '60501');
UPDATE `war_world`.`creature_protos` SET `MinLevel` = '40', `MaxLevel` = '40' WHERE (`Entry` = '98323');
UPDATE `war_world`.`creature_items` SET `ModelId` = '7189' WHERE (`Entry` = '98323') and (`SlotId` = '24');
UPDATE `war_world`.`creature_items` SET `ModelId` = '7185' WHERE (`Entry` = '98323') and (`SlotId` = '28');
UPDATE `war_world`.`creature_items` SET `ModelId` = '7190' WHERE (`Entry` = '98323') and (`SlotId` = '27');
UPDATE `war_world`.`creature_items` SET `ModelId` = '7186' WHERE (`Entry` = '98323') and (`SlotId` = '20');
UPDATE `war_world`.`creature_items` SET `ModelId` = '7187' WHERE (`Entry` = '98323') and (`SlotId` = '22');
UPDATE `war_world`.`creature_items` SET `ModelId` = '7188' WHERE (`Entry` = '98323') and (`SlotId` = '21');
UPDATE `war_world`.`creature_items` SET `ModelId` = '7184' WHERE (`Entry` = '98323') and (`SlotId` = '23');
UPDATE `war_world`.`creature_items` SET `ModelId` = '8819' WHERE (`Entry` = '98323') and (`SlotId` = '10');
UPDATE `war_world`.`creature_items` SET `ModelId` = '8811' WHERE (`Entry` = '98323') and (`SlotId` = '11');
UPDATE `war_world`.`quests` SET `Active` = '1' WHERE (`Entry` = '60501');
