UPDATE `war_world`.`player_keep_spawn` SET `OrderFeedZoneId` = '109', `DestructionFeedZoneId` = '109' WHERE (`KeepId` = '100');
UPDATE `war_world`.`player_keep_spawn` SET `OrderFeedZoneId` = '103', `DestructionFeedZoneId` = '103' WHERE (`KeepId` = '101');
UPDATE `war_world`.`player_keep_spawn` SET `OrderFeedZoneId` = '9', `DestructionFeedZoneId` = '9' WHERE (`KeepId` = '102');
UPDATE `war_world`.`player_keep_spawn` SET `OrderFeedZoneId` = '3', `DestructionFeedZoneId` = '3' WHERE (`KeepId` = '103');
UPDATE `war_world`.`player_keep_spawn` SET `OrderFeedZoneId` = '209', `DestructionFeedZoneId` = '209' WHERE (`KeepId` = '104');
UPDATE `war_world`.`player_keep_spawn` SET `OrderFeedZoneId` = '203', `DestructionFeedZoneId` = '203' WHERE (`KeepId` = '105');
UPDATE `war_world`.`player_keep_spawn` SET `OrderFeedZoneId` = '203', `DestructionFeedZoneId` = '203' WHERE (`KeepId` = '104');
UPDATE `war_world`.`player_keep_spawn` SET `OrderFeedZoneId` = '209', `DestructionFeedZoneId` = '209' WHERE (`KeepId` = '105');
UPDATE `war_world`.`player_keep_spawn` SET `OrderFeedZoneId` = '3', `DestructionFeedZoneId` = '3' WHERE (`KeepId` = '102');
UPDATE `war_world`.`player_keep_spawn` SET `OrderFeedZoneId` = '9', `DestructionFeedZoneId` = '9' WHERE (`KeepId` = '103');

update player_keep_spawn set orderfeedzoneid = 9, DestructionFeedZoneId=9 where keepid = 5;
update player_keep_spawn set orderfeedzoneid = 9, DestructionFeedZoneId=9 where keepid = 6;
update player_keep_spawn set orderfeedzoneid = 5, DestructionFeedZoneId=5 where keepid = 7;
update player_keep_spawn set orderfeedzoneid = 5, DestructionFeedZoneId=5 where keepid = 8;
update player_keep_spawn set orderfeedzoneid = 3, DestructionFeedZoneId=3 where keepid = 9;
update player_keep_spawn set orderfeedzoneid = 3, DestructionFeedZoneId=3 where keepid = 10;
update player_keep_spawn set orderfeedzoneid = 109, DestructionFeedZoneId=109 where keepid = 15;
update player_keep_spawn set orderfeedzoneid = 109, DestructionFeedZoneId=109 where keepid = 16;
update player_keep_spawn set orderfeedzoneid = 105, DestructionFeedZoneId=105 where keepid = 17;
update player_keep_spawn set orderfeedzoneid = 105, DestructionFeedZoneId=105 where keepid = 18;
update player_keep_spawn set orderfeedzoneid = 103, DestructionFeedZoneId=103 where keepid = 19;
update player_keep_spawn set orderfeedzoneid = 103, DestructionFeedZoneId=103 where keepid = 20;
update player_keep_spawn set orderfeedzoneid = 209, DestructionFeedZoneId=209 where keepid = 25;
update player_keep_spawn set orderfeedzoneid = 209, DestructionFeedZoneId=209 where keepid = 26;
update player_keep_spawn set orderfeedzoneid = 205, DestructionFeedZoneId=205 where keepid = 27;
update player_keep_spawn set orderfeedzoneid = 205, DestructionFeedZoneId=205 where keepid = 28;
update player_keep_spawn set orderfeedzoneid = 203, DestructionFeedZoneId=203 where keepid = 29;
update player_keep_spawn set orderfeedzoneid = 203, DestructionFeedZoneId=203 where keepid = 30;
