DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '433');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '434');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '435');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '436');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '437');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '438');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '439');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '440');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '441');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '442');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '443');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '444');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '445');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '446');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '447');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '448');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '449');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '450');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '451');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '452');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '453');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '454');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '455');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '456');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '505');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '507');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1521');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1522');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1523');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1524');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1525');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1526');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1527');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1528');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1529');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1530');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1531');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1532');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1533');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1534');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1535');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1536');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1569');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1570');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1571');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1572');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1573');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1574');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1575');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1576');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1577');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1578');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1579');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1580');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1581');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1582');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1583');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1584');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1585');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1586');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1587');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1588');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1589');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1590');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1595');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1596');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1597');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1598');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1599');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1600');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1601');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1602');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1603');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1604');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1605');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1606');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1607');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1608');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1609');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1610');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1611');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1612');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1613');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1614');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1615');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1616');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1617');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1618');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1619');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1620');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1621');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1622');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1623');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1624');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1625');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1626');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1627');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1628');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '1629');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '2001');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '2002');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '2003');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '2004');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '2005');
DELETE FROM `war_world`.`rvr_reward_keep_items` WHERE (`RewardId` = '2006');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('433', '4', '0', '1', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('434', '4', '0', '2', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('435', '4', '0', '3', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('436', '4', '0', '4', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('437', '4', '0', '5', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('438', '4', '0', '6', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('439', '4', '0', '7', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('440', '4', '0', '8', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('441', '4', '0', '9', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('442', '4', '0', '10', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('443', '4', '0', '11', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('444', '4', '0', '12', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('445', '4', '0', '13', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('446', '4', '0', '14', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('447', '4', '0', '15', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('448', '4', '0', '16', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('449', '4', '0', '17', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('450', '4', '0', '18', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('451', '4', '0', '19', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('452', '4', '0', '20', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('453', '4', '0', '21', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('454', '4', '0', '22', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('455', '4', '0', '23', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('456', '4', '0', '24', '208429', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('505', '2', '0', '0', '84905', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('507', '2', '0', '0', '908905', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1521', '3', '0', '1', '640660', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1522', '3', '0', '2', '640660', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1523', '3', '0', '5', '640660', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1524', '3', '0', '6', '640660', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1525', '3', '0', '9', '640660', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1526', '3', '0', '10', '640660', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1527', '3', '0', '12', '640660', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1528', '3', '0', '13', '640660', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1529', '3', '0', '14', '640660', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1530', '3', '0', '17', '640660', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1531', '3', '0', '18', '640660', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1532', '3', '0', '8', '640660', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1533', '3', '0', '19', '640660', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1534', '3', '0', '21', '640660', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1535', '3', '0', '22', '640660', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1536', '3', '0', '23', '640660', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1569', '3', '0', '1', '640663', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1570', '3', '0', '2', '640663', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1571', '3', '0', '5', '640663', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1572', '3', '0', '6', '640663', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1573', '3', '0', '9', '640663', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1574', '3', '0', '10', '640663', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1575', '3', '0', '12', '640663', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1576', '3', '0', '13', '640663', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1577', '3', '0', '14', '640663', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1578', '3', '0', '17', '640663', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1579', '3', '0', '18', '640663', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1580', '3', '0', '8', '640663', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1581', '3', '0', '19', '640663', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1582', '3', '0', '21', '640663', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1583', '3', '0', '22', '640663', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1584', '3', '0', '23', '640663', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1585', '3', '0', '3', '640664', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1586', '3', '0', '7', '640664', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1587', '3', '0', '12', '640664', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1588', '3', '0', '15', '640664', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1589', '3', '0', '20', '640664', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1590', '3', '0', '23', '640664', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1595', '3', '0', '8', '640666', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1596', '3', '0', '18', '640666', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1597', '3', '0', '4', '640666', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1598', '3', '0', '4', '640667', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1599', '3', '0', '8', '640667', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1600', '3', '0', '18', '640667', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1601', '3', '0', '3', '640668', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1602', '3', '0', '7', '640668', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1603', '3', '0', '11', '640668', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1604', '3', '0', '15', '640668', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1605', '3', '0', '16', '640668', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1606', '3', '0', '20', '640668', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1607', '3', '0', '24', '640668', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1608', '3', '0', '7', '640669', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1609', '3', '0', '20', '640669', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1610', '3', '0', '3', '640669', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1611', '3', '0', '15', '640669', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1612', '3', '0', '1', '640670', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1613', '3', '0', '2', '640670', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1614', '3', '0', '5', '640670', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1615', '3', '0', '6', '640670', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1616', '3', '0', '9', '640670', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1617', '3', '0', '10', '640670', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1618', '3', '0', '12', '640670', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1619', '3', '0', '13', '640670', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1620', '3', '0', '14', '640670', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1621', '3', '0', '17', '640670', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1622', '3', '0', '18', '640670', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1623', '3', '0', '8', '640670', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1624', '3', '0', '19', '640670', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1625', '3', '0', '21', '640670', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1626', '3', '0', '22', '640670', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1627', '3', '0', '23', '640670', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1628', '3', '0', '12', '640671', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('1629', '3', '0', '23', '640671', '1', '0');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('2001', '1', '0', '0', '208470', '2', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('2002', '1', '0', '0', '208470', '5', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('2003', '1', '0', '0', '208470', '10', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('2004', '2', '0', '0', '208470', '15', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('2005', '1', '0', '0', '84905', '1', '1');
INSERT INTO `war_world`.`rvr_reward_keep_items` (`RewardId`, `Rarity`, `RRBand`, `Class`, `ItemId`, `ItemCount`, `CanAwardDuplicate`) VALUES ('2006', '1', '0', '0', '908905', '1', '1');
