INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `InvokeOn`, `Target`, `EffectRadius`, `EventIDString`, `EventChance`, `BuffLine`) VALUES ('10103', 'Impairment VII', '0', '0', 'InvokeBuff', '10533', '0', 'EventInstigator', '0', 'DirectDamageDealt', '5', '1');
INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `InvokeOn`, `Target`, `BuffLine`) VALUES ('10531', 'Impairment VII Proc', '0', '0', 'DamageOverTime', '7', 'Host', '1');
INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `InvokeOn`, `Target`, `BuffLine`) VALUES ('10531', 'Impairment VII Proc', '1', '0', 'ModifySpeed', '-46', '5', 'Host', '2');
INSERT INTO `war_world`.`buff_infos` (`Entry`, `Name`, `BuffClassString`, `MaxCopies`, `MaxStack`, `PersistsOnDeath`) VALUES ('10103', 'Impairment VII', 'Career', '1', '1', '1');
INSERT INTO `war_world`.`buff_infos` (`Entry`, `Name`, `Group`, `MaxStack`, `Duration`, `Interval`, `Silent`) VALUES ('10531', 'Impairment VII Proc', '30', '1', '9', '3000', '1');
INSERT INTO `war_world`.`ability_damage_heals` (`Entry`, `Index`, `Name`, `MinDamage`, `MaxDamage`, `DamageType`, `ParentCommandID`, `ParentCommandSequence`, `NoCrits`, `HatredScale`, `HealHatredScale`) VALUES ('10531', '1', 'Impairment VII Proc', '132', '132', 'Physical', '0', '0', '1', '1', '1');
INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `InvokeOn`, `Target`, `EffectRadius`, `EventIDString`, `EventChance`, `BuffLine`) VALUES ('10007', 'Hemorrage VII', '0', '0', 'InvokeBuff', '10489', '0', 'EventInstigator', '0', 'DirectDamageDealt', '5', '1');
INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `InvokeOn`, `Target`, `BuffLine`) VALUES ('10487', 'Hemorrage VII Proc', '0', '0', 'DamageOverTime', '7', 'Host', '1');
INSERT INTO `war_world`.`buff_infos` (`Entry`, `Name`, `BuffClassString`, `MaxCopies`, `MaxStack`, `PersistsOnDeath`) VALUES ('10007', 'Hemorrage VII', 'Career', '1', '1', '1');
INSERT INTO `war_world`.`buff_infos` (`Entry`, `Name`, `Group`, `MaxStack`, `Duration`, `Interval`, `Silent`) VALUES ('10487', 'Hemorrage VII Proc', '30', '1', '9', '3000', '1');
INSERT INTO `war_world`.`ability_damage_heals` (`Entry`, `Index`, `Name`, `MinDamage`, `MaxDamage`, `DamageType`, `ParentCommandID`, `ParentCommandSequence`, `NoCrits`, `HatredScale`, `HealHatredScale`) VALUES ('10487', '1', 'Hemorrage VII Proc', '399', '399', 'Physical', '0', '0', '1', '1', '1');
UPDATE `war_world`.`item_infos` SET `Effects` = '10103' WHERE (`Entry` = '475088');
UPDATE `war_world`.`item_infos` SET `Effects` = '10007' WHERE (`Entry` = '476528');
UPDATE `war_world`.`item_infos` SET `Stats` = '8:37;31:1;77:3;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;' WHERE (`Entry` = '475088');
UPDATE `war_world`.`buff_commands` SET `PrimaryValue` = '10531' WHERE (`Entry` = '10103') and (`CommandID` = '0') and (`CommandSequence` = '0');
UPDATE `war_world`.`buff_commands` SET `PrimaryValue` = '10487' WHERE (`Entry` = '10007') and (`CommandID` = '0') and (`CommandSequence` = '0');
UPDATE `war_world`.`item_infos` SET `Stats` = '8:37;31:1;77:3;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;' WHERE (`Entry` = '475136');
UPDATE `war_world`.`item_infos` SET `Stats` = '8:37;31:1;77:3;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;' WHERE (`Entry` = '475094');
UPDATE `war_world`.`item_infos` SET `Effects` = '10161' WHERE (`Entry` = '475094');
UPDATE `war_world`.`item_infos` SET `Effects` = '10161' WHERE (`Entry` = '475136');

