using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using RpcSourceGenerator;

namespace Core.Infrastructure.Network.RpcSourceGenerator.Tests;

public class RpcClientGeneratorSnapshotTests
{
    private static readonly string ClientBaseCode = @"
namespace Core.Infrastructure.Network
{
    public abstract class Client
    {
        protected void SendRequest<T>(byte opcode, T request) { }
        protected TResponse SendRequest<TRequest, TResponse>(byte requestOpcode, byte responseOpcode, TRequest request) { return default!; }
        protected System.Threading.Tasks.Task SendRequestAsync<T>(byte opcode, T request) { return System.Threading.Tasks.Task.CompletedTask; }
        protected System.Threading.Tasks.Task<TResponse> SendRequestAsync<TRequest, TResponse>(byte requestOpcode, byte responseOpcode, TRequest request) { return System.Threading.Tasks.Task.FromResult<TResponse>(default!); }
    }
    
    [System.AttributeUsage(System.AttributeTargets.Method)]
    public class RpcAttribute : System.Attribute
    {
        public byte Opcode { get; }
        public byte? ResponseOpcode { get; }
        public RpcAttribute(byte opcode) { Opcode = opcode; }
        public RpcAttribute(byte opcode, byte responseOpcode) { Opcode = opcode; ResponseOpcode = responseOpcode; }
    }
}";

    [Fact]
    public Task GeneratesCompleteClientProxy()
    {
        var source = @"
using System.Threading.Tasks;
using Core.Infrastructure.Network;

namespace TestNamespace
{
    public class PingRequest { }
    public class PingResponse { }
    public class LoginRequest { }
    public class LoginResponse { }
    public class NotifyRequest { }
    
    public partial class GameClient : Client
    {
        [Rpc(0x01, 0x02)]
        public partial Task<PingResponse> Ping(PingRequest request);

        [Rpc(0x10, 0x11)]
        public partial Task<LoginResponse> Login(LoginRequest request);

        [Rpc(0x20)]
        public partial Task Notify(NotifyRequest request);
        
        [Rpc(0x30)]
        public partial Task NotifyNoParam();

        [Rpc(0x40, 0x41)]
        internal partial Task<LoginResponse> InternalLogin(LoginRequest request);
    }
}";

        var result = RunGenerator(source);
        var generatedCode = result.GeneratedTrees.Single().ToString();
        
        return Verify(generatedCode)
            .UseDirectory("Snapshots")
            .ScrubLines(line => line.Contains("// <auto-generated"));
    }

    private GeneratorTestResult RunGenerator(string source)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(source);
        var references = AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => !a.IsDynamic && !string.IsNullOrWhiteSpace(a.Location))
            .Select(a => MetadataReference.CreateFromFile(a.Location))
            .ToList();

        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            new[] { syntaxTree, CSharpSyntaxTree.ParseText(ClientBaseCode) },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new RpcClientGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation);

        var result = driver.GetRunResult();
        return new GeneratorTestResult
        {
            Diagnostics = result.Diagnostics,
            GeneratedTrees = result.Results[0].GeneratedSources.Select(s => s.SyntaxTree).ToArray()
        };
    }

    private class GeneratorTestResult
    {
        public ImmutableArray<Diagnostic> Diagnostics { get; init; }
        public SyntaxTree[] GeneratedTrees { get; init; } = Array.Empty<SyntaxTree>();
    }
}
