using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Core.Infrastructure.Network.RpcSourceGenerator.Tests;

public class RpcServerGeneratorSnapshotTests
{
    private static readonly string HandlerBaseCode = @"
namespace Core.Infrastructure.Network
{
    public interface IPacketHandler { }

    [System.AttributeUsage(System.AttributeTargets.Method)]
    public class RpcAttribute : System.Attribute
    {
        public byte Opcode { get; }
        public byte? ResponseOpcode { get; }
        public RpcAttribute(byte opcode) { Opcode = opcode; }
        public RpcAttribute(byte opcode, byte responseOpcode) { Opcode = opcode; ResponseOpcode = responseOpcode; }
    }

    [System.AttributeUsage(System.AttributeTargets.Parameter)]
    public class FromServicesAttribute : System.Attribute { }

    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    public class PacketGroupAttribute : System.Attribute
    {
        public string GroupName { get; }
        public PacketGroupAttribute(string groupName = ""Default"") { GroupName = groupName; }
    }

    public interface IPacketSerializer
    {
        T Deserialize<T>(System.ReadOnlySpan<byte> data);
        void Serialize<T>(System.Buffers.IBufferWriter<byte> writer, T value);
    }

    public interface IConnectionContext
    {
        string RemoteAddress { get; }
        void SendResponse<T>(byte opcode, T response);
        void Disconnect(object reason);
        System.Collections.Generic.IDictionary<string, object> Items { get; }
        void OnDispatchError(byte opcode, System.Exception exception);
    }

    public interface IPacketDispatcher
    {
        void Dispatch(byte opcode, System.ReadOnlyMemory<byte> payload,
            System.IServiceProvider services, IPacketSerializer serializer, IConnectionContext connection);
    }
}

namespace Microsoft.Extensions.DependencyInjection
{
    public interface IServiceScope : System.IDisposable
    {
        System.IServiceProvider ServiceProvider { get; }
    }

    public interface IServiceCollection { }

    public static class ServiceProviderServiceExtensions
    {
        public static IServiceScope CreateScope(this System.IServiceProvider provider) => null;
        public static T GetRequiredService<T>(this System.IServiceProvider provider) => default;
    }

    public static class ServiceCollectionServiceExtensions
    {
        public static IServiceCollection AddSingleton<TService, TImplementation>(this IServiceCollection services) => services;
        public static IServiceCollection AddScoped<TService>(this IServiceCollection services) => services;
    }
}";

    [Fact]
    public Task GeneratesCompleteRpcHandler()
    {
        var source = @"
using System;
using System.Threading.Tasks;
using Core.Infrastructure.Network;

namespace TestNamespace
{
    public class PingRequest { }
    public class PingResponse { }
    public class LoginRequest { }
    public class LoginResponse { }
    public class NotifyRequest { }
    public class MyService { }

    public partial class GameHandler : Core.Infrastructure.Network.IPacketHandler
    {
        [Rpc(0x01)]
        public void HandlePing()
        {
            // Ping handler
        }

        [Rpc(0x10, 0x11)]
        public LoginResponse HandleLogin(LoginRequest request)
        {
            return new LoginResponse();
        }

        [Rpc(0x20, 0x21)]
        public async Task<PingResponse> HandlePingAsync(PingRequest request)
        {
            await Task.Delay(10);
            return new PingResponse();
        }

        [Rpc(0x30)]
        public async Task HandleNotifyAsync(NotifyRequest request)
        {
            await Task.Delay(10);
        }

        [Rpc(0x40, 0x41)]
        public async Task<LoginResponse> HandleWithServices([FromServices] MyService svc, IConnectionContext context)
        {
            return await Task.FromResult(new LoginResponse());
        }
    }
}";

        var result = RunGenerator(source);
        var generatedCode = result.GeneratedTrees.Single().ToString();

        return Verify(generatedCode)
            .UseDirectory("Snapshots")
            .ScrubLines(line =>
                line.Contains("// <auto-generated") ||
                line.Contains("#nullable"));
    }

    private GeneratorTestResult RunGenerator(string source)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(source);
        var references = AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => !a.IsDynamic && !string.IsNullOrWhiteSpace(a.Location))
            .Select(a => MetadataReference.CreateFromFile(a.Location))
            .ToList();

        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            new[] { syntaxTree, CSharpSyntaxTree.ParseText(HandlerBaseCode) },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new global::RpcSourceGenerator.RpcServerGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation);

        var result = driver.GetRunResult();
        return new GeneratorTestResult
        {
            Diagnostics = result.Diagnostics,
            GeneratedTrees = result.Results[0].GeneratedSources.Select(s => s.SyntaxTree).ToArray()
        };
    }

    private class GeneratorTestResult
    {
        public ImmutableArray<Diagnostic> Diagnostics { get; init; }
        public SyntaxTree[] GeneratedTrees { get; init; } = Array.Empty<SyntaxTree>();
    }
}
