<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <AppDesignerFolder>Properties</AppDesignerFolder>
        <RootNamespace>WorldServer</RootNamespace>
        <AssemblyName>WorldServer</AssemblyName>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <PropertyGroup>
        <ApplicationIcon>world.ico</ApplicationIcon>
    </PropertyGroup>
    <PropertyGroup>
        <StartupObject>WorldServer.Core</StartupObject>
    </PropertyGroup>
    <ItemGroup>
        <Protobuf Include="..\..\AccountMgr.proto" GrpcServices="Client"/>
    </ItemGroup>
    <ItemGroup>
        <None Include="app.config"/>
        <None Include="NLog.config">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <SubType>Designer</SubType>
        </None>
        <None Include="NLog.xsd">
            <SubType>Designer</SubType>
        </None>
        <None Include="packages.config"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\AccountCacher\AccountCacher.csproj">
            <Project>{174C9135-A25B-4842-BD53-EA1EA133A5F5}</Project>
            <Name>AccountCacher</Name>
        </ProjectReference>
        <ProjectReference Include="..\Common\Common.csproj">
            <Project>{8bc085cd-429b-41d1-bb47-9621fd32ec23}</Project>
            <Name>Common</Name>
        </ProjectReference>
        <ProjectReference Include="..\FrameWork\FrameWork.csproj">
            <Project>{d5c98f3a-d5d2-4aed-a5a7-06d2de095095}</Project>
            <Name>FrameWork</Name>
        </ProjectReference>
    </ItemGroup>
    <ItemGroup>
        <Content Include="Abilities\Chaos humans login-logout all classes.txt">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="Abilities\Dark elves login-logout all classes.txt">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="Abilities\Dwarves and their classes login-logout.txt">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="Abilities\High elves and their classes login-logout.txt">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="Abilities\Humans and their classes login-logout.txt">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="Abilities\Orcs login-logout all classes.txt">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="Configs\LocalDevelopment\Account.xml"/>
        <Content Include="Configs\LocalDevelopment\Launcher.xml"/>
        <Content Include="Configs\LocalDevelopment\Lobby.xml"/>
        <Content Include="Configs\LocalDevelopment\World.xml"/>
        <Content Include="WarZone.dll">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="world.ico"/>
    </ItemGroup>
    <ItemGroup>
        <WCFMetadata Include="Connected Services\"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Appccelerate.StateMachine" Version="6.0.0"/>
        <PackageReference Include="BehaviourTree" Version="1.0.73"/>
        <PackageReference Include="BulletSharp" Version="0.11.1"/>
        <PackageReference Include="Grpc.Net.Client" Version="2.71.0"/>
        <PackageReference Include="Grpc.Tools" Version="2.72.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageReference Include="NLog" Version="6.0.4"/>
        <PackageReference Include="System.CodeDom" Version="8.0.0" />
        <PackageReference Include="System.Drawing.Common" Version="8.0.20"/>
    </ItemGroup>
</Project>