<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Launcher</RootNamespace>
    <AssemblyName>Launcher</AssemblyName>
    <ApplicationIcon>WAR.ico</ApplicationIcon>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>bin\Debug</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\bin\Release\Launcher\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="HashCreator">
      <HintPath>..\deps\EasyMyp\HashCreator.dll</HintPath>
    </Reference>
    <Reference Include="HashDictionary">
      <HintPath>..\deps\EasyMyp\HashDictionary.dll</HintPath>
    </Reference>
    <Reference Include="ICSharpCode.SharpZipLib">
      <HintPath>..\deps\EasyMyp\ICSharpCode.SharpZipLib.dll</HintPath>
    </Reference>
    <Reference Include="MYPHandler">
      <HintPath>..\deps\EasyMyp\MYPHandler.dll</HintPath>
    </Reference>
    <Reference Include="WarhammerOnlineHash">
      <HintPath>..\deps\EasyMyp\WarhammerOnlineHash.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.1.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.1" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Core.Infrastructure.Network\Core.Infrastructure.Network.csproj" />
    <ProjectReference Include="..\FrameWork\FrameWork.csproj" />
    <ProjectReference Include="..\LauncherServer.Dtos\LauncherServer.Dtos.csproj" />
    <ProjectReference Include="..\Core.Infrastructure.Network.RpcSourceGenerators\Core.Infrastructure.Network.RpcSourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <None Update="NLog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NLog.xsd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Strings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
