-- Fixes name for Last Screening Potion

UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '184840');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '184845');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '184850');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '184855');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '184860');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '197332');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003114');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003119');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003124');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003129');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003134');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003139');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003144');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003149');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003154');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003159');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003164');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '157830');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '157835');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '157840');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '157845');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '157850');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '157855');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '157860');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '197312');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '197317');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '197307');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003009');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003014');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003019');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003024');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003029');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003034');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003039');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003044');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003049');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003054');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '189730');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '189735');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '189740');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '189745');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '189750');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '189755');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '189760');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '197347');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '197352');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003059');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003064');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003069');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003074');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003079');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003084');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003089');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003094');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003099');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003104');
UPDATE `war_world`.`item_infos` SET `Name` = 'Lasting Screening Potion' WHERE (`Entry` = '3003109');

-- Surrounds you with a magical barrier buff that will absorb incoming damage.
-- Name fix

UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '157825');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '157830');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '157835');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '157840');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '157845');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '157850');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '157855');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '157860');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '184840');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '184845');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '184850');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '184855');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '184860');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '189730');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '189735');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '189740');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '189745');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '189750');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '189755');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '189760');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '197312');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '197317');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '197332');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '197347');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '197352');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '197307');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003004');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003059');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003114');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003009');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003064');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003119');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003014');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003069');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003124');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003019');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003074');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003129');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003024');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003079');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003134');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003029');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003084');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003139');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003034');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003089');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003144');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003039');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003094');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003149');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003044');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003099');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003154');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003049');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003104');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003159');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003054');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003109');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage.' WHERE (`Entry` = '3003164');

-- Item Level = MinLevel + Rarity - 1
-- Rarity one potions adjusted.
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 184840' WHERE (`Entry` = '3003129');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 184845' WHERE (`Entry` = '3003134');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 184850' WHERE (`Entry` = '3003139');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 184855' WHERE (`Entry` = '3003144');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 184860' WHERE (`Entry` = '3003149');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 197332' WHERE (`Entry` = '3003159');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '184840');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '184845');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '184855');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '184850');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '184860');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '197332');
UPDATE `war_world`.`item_infos` SET `ObjectLevel` = '1' WHERE (`Entry` = '3003114');
UPDATE `war_world`.`item_infos` SET `ObjectLevel` = '5' WHERE (`Entry` = '3003119');

-- Rarity two potions adjusted.
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 157825', `ObjectLevel` = '2' WHERE (`Entry` = '3003004');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 157830', `ObjectLevel` = '6' WHERE (`Entry` = '3003009');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 157835', `ObjectLevel` = '11' WHERE (`Entry` = '3003014');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 157840' WHERE (`Entry` = '3003019');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 157845', `ObjectLevel` = '21' WHERE (`Entry` = '3003024');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 157850', `ObjectLevel` = '26' WHERE (`Entry` = '3003029');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 157855', `ObjectLevel` = '31' WHERE (`Entry` = '3003034');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 157860', `ObjectLevel` = '33' WHERE (`Entry` = '3003039');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 197307' WHERE (`Entry` = '3003044');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 197312', `ObjectLevel` = '39' WHERE (`Entry` = '3003049');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 197317', `ObjectLevel` = '41' WHERE (`Entry` = '3003054');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '2', `TwoHanded` = '0', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '157825');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '6', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '157830');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '11', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '157835');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '157840');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '21', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '157845');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '26', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '157850');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '31', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '157855');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '33', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '157860');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '41', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '197317');
UPDATE `war_world`.`item_infos` SET `ObjectLevel` = '39', `Crafts` = NULL, `ItemSet` = NULL, `BaseColor1` = NULL, `BaseColor2` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '197312');
UPDATE `war_world`.`item_infos` SET `Crafts` = NULL, `SellRequiredItems` = NULL, `ItemSet` = NULL, `BaseColor1` = NULL, `BaseColor2` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '197307');

-- Rarity three potions adjusted.
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 189730', `ObjectLevel` = '7' WHERE (`Entry` = '3003064');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 189735', `ObjectLevel` = '12' WHERE (`Entry` = '3003069');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 189740', `ObjectLevel` = '17' WHERE (`Entry` = '3003074');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 189745', `ObjectLevel` = '22' WHERE (`Entry` = '3003079');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 189750', `ObjectLevel` = '27' WHERE (`Entry` = '3003084');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 189755', `ObjectLevel` = '32' WHERE (`Entry` = '3003089');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 189760', `ObjectLevel` = '34' WHERE (`Entry` = '3003094');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 197347', `ObjectLevel` = '37' WHERE (`Entry` = '3003099');
UPDATE `war_world`.`item_infos` SET `Description` = 'Surrounds you with a magical barrier buff that will absorb incoming damage. DUPLICATE TRACE TO 197352', `ObjectLevel` = '40' WHERE (`Entry` = '3003104');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '7', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '189730');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '12', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '189735');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '17', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '189740');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '22', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '189745');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '27', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '189750');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '32', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '189755');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '34', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '189760');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '37', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '197347');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '40', `ItemSet` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '197352');
UPDATE `war_world`.`item_infos` SET `Stats` = '', `ObjectLevel` = '42', `Crafts` = NULL, `SellRequiredItems` = NULL, `ItemSet` = NULL, `Craftresult` = NULL, `DyeAble` = NULL, `Salvageable` = NULL, `BaseColor1` = NULL, `BaseColor2` = NULL, `TokUnlock` = NULL WHERE (`Entry` = '3003109');
UPDATE `war_world`.`item_infos` SET `ObjectLevel` = '3' WHERE (`Entry` = '3003059');

-- Chapter 1 Correction
DELETE FROM `war_world`.`item_infos` WHERE (`Entry` = '190470');
UPDATE `war_world`.`chapter_rewards` SET `ItemId` = '189730' WHERE (`Entry` = '101') and (`ItemId` = '190470');
UPDATE `war_world`.`chapter_rewards` SET `ItemId` = '189730' WHERE (`Entry` = '201') and (`ItemId` = '190470');
UPDATE `war_world`.`chapter_rewards` SET `ItemId` = '189730' WHERE (`Entry` = '301') and (`ItemId` = '190470');
UPDATE `war_world`.`chapter_rewards` SET `ItemId` = '189730' WHERE (`Entry` = '401') and (`ItemId` = '190470');
UPDATE `war_world`.`chapter_rewards` SET `ItemId` = '189730' WHERE (`Entry` = '501') and (`ItemId` = '190470');
UPDATE `war_world`.`chapter_rewards` SET `ItemId` = '189730' WHERE (`Entry` = '601') and (`ItemId` = '190470');

-- Rarity four and five added.
INSERT INTO `war_world`.`item_infos` (`Entry`, `Name`, `Description`, `Type`, `Race`, `ModelId`, `SlotId`, `Rarity`, `Career`, `Skills`, `Bind`, `Armor`, `SpellId`, `Dps`, `Speed`, `MinRank`, `MinRenown`, `StartQuest`, `Stats`, `SellPrice`, `TalismanSlots`, `MaxStack`, `ObjectLevel`, `UniqueEquiped`, `Unk27`, `TwoHanded`, `TokUnlock2`, `IsSiege`) VALUES ('2021000760', 'Lasting Screening Potion', 'Surrounds you with a magical barrier buff that will absorb incoming damage.', '31', '0', '760', '0', '4', '0', '0', '0', '0', '7896', '0', '0', '40', '0', '0', '', '45', '0', '20', '43', '0', '0 1 0 1 3 2 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0', '0', '0', '0');
INSERT INTO `war_world`.`item_infos` (`Entry`, `Name`, `Description`, `Type`, `Race`, `ModelId`, `SlotId`, `Rarity`, `Career`, `Skills`, `Bind`, `Armor`, `SpellId`, `Dps`, `Speed`, `MinRank`, `MinRenown`, `StartQuest`, `Stats`, `SellPrice`, `TalismanSlots`, `MaxStack`, `ObjectLevel`, `UniqueEquiped`, `Unk27`, `TwoHanded`, `TokUnlock2`, `IsSiege`) VALUES ('2021001760', 'Lasting Screening Potion', 'Surrounds you with a magical barrier buff that will absorb incoming damage.', '31', '0', '760', '0', '5', '0', '0', '0', '0', '7896', '0', '0', '40', '0', '0', '', '45', '0', '20', '44', '0', '0 1 0 1 3 2 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0', '0', '0', '0');

