DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '3650');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '7358');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '8530');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '16078');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '16081');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '19409');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '33182');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '45084');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '45224');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '46325');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '46327');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '48112');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '49164');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '64106');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '2000687');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '2000690');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '2000692');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '2000706');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '2000707');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '2000708');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '2000712');
DELETE FROM `boss_spawn` WHERE (`BossSpawnId` = '2000751');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('3650', '3650', '3', 'The Bulbous One', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('7358', '7358', '9', 'Grydal Bloodshroud^M', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('8530', '8530', '15', 'Juggernaut^n', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('16078', '16078', '17', 'Wrackspite^M', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('16081', '16081', '7', 'Beastrip^M', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('19409', '19409', '2', 'Kokrit', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('33182', '33182', '1', 'Goremane', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('45084', '45084', '8', 'Thar''lgnan^M', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('45224', '45224', '6', 'Gahlvoth Darkrage^M', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('46325', '46325', '20', 'Zekaraz the Bloodcaller^M', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('46327', '46327', '19', 'Clawfang^M', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('48112', '48112', '16', 'Lord Slaurith^M', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('49164', '49164', '14', 'Chorek the Unstoppable^M', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('64106', '64106', '22', 'Skull Lord Var''Ithrok', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('2000687', '2000687', '4', 'Azuk''Thul^M', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('2000690', '2000690', '5', 'SummonBorzhar', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('2000692', '2000692', '18', 'Doomspike^M', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('2000706', '2000706', '10', 'Urlf Daemonblessed^M', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('2000707', '2000707', '11', 'Garithex the Mountain^M', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('2000708', '2000708', '12', 'Hargan the Furious^M', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('2000712', '2000712', '13', 'Skulltaker Bloodgiant^m', '1');
INSERT INTO `boss_spawn` (`BossSpawnId`, `ProtoId`, `SpawnGuid`, `Name`, `Enabled`) VALUES ('2000751', '2000751', '21', 'Kaarn the Vanquisher^M', '1');
