DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2000');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2001');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2002');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2003');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2004');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2005');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2006');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2007');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2008');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2009');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2010');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2011');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2012');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2013');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2015');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2100');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2101');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2102');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2103');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2104');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2105');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2106');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2107');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2108');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2109');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2110');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2111');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2123');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2136');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2200');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2201');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2202');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2203');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2204');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2205');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2206');
DELETE FROM `scenario_infos` WHERE (`ScenarioID` = '2207');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2000', 'Gates of Ekrund', '1', '40', '0', '12', '1', '4', '30', '5', '1', '0', '0', '0', '30');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2001', 'Mourkain Temple', '1', '40', '0', '12', '2', '4', '31', '10', '1', '0', '0', '0', '31');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2002', 'Black Fire Basin', '1', '40', '0', '12', '10', '4', '38', '1', '1', '0', '0', '0', '38');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2003', 'Kadrin Valley Pass', '1', '40', '0', '12', '6', '4', '36', '5', '1', '0', '0', '0', '36');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2004', 'Gromril Crossing', '1', '40', '0', '12', '6', '4', '43', '2', '1', '0', '0', '0', '43');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2005', 'Thunder Valley', '1', '40', '0', '12', '1', '4', '34', '5', '1', '0', '0', '0', '34');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2006', 'Logrin\'s Forge', '1', '40', '0', '12', '3', '4', '39', '2', '1', '0', '0', '0', '39');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2007', 'Black Crag Keep', '1', '40', '0', '12', '1', '4', '37', '5', '1', '0', '0', '0', '37');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2008', 'Howling Gorge', '1', '40', '0', '12', '4', '4', '44', '2', '1', '0', '0', '0', '44');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2009', 'Karaz-a-Karak Gates', '1', '40', '0', '12', '1', '4', '0', '0', '1', '0', '0', '0', '0');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2010', 'Eight Peaks Gates', '1', '40', '0', '12', '1', '4', '0', '0', '1', '0', '0', '0', '0');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2011', 'Doomfist Crater', '1', '40', '0', '12', '1', '4', '33', '2', '1', '0', '0', '0', '33');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2012', 'Altdorf War Quarters', '1', '40', '0', '24', '6', '4', '41', '0', '1', '0', '1', '0', '41');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2013', 'The Undercroft', '1', '40', '0', '24', '6', '4', '42', '0', '1', '0', '0', '0', '42');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2015', 'The Ironclad', '1', '40', '0', '12', '1', '4', '32', '5', '1', '0', '0', '0', '32');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2100', 'Nordenwatch', '1', '40', '0', '12', '1', '4', '130', '5', '1', '0', '0', '0', '130');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2101', 'Stonetroll Crossing', '1', '40', '0', '12', '9', '4', '131', '2', '1', '0', '0', '0', '131');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2102', 'Talabec Dam', '1', '40', '0', '12', '4', '4', '132', '2', '1', '0', '0', '0', '132');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2103', 'High Pass Cemetery', '1', '40', '0', '12', '3', '4', '139', '5', '1', '0', '0', '0', '139');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2104', 'Maw of Madness', '1', '40', '0', '12', '2', '4', '133', '5', '1', '0', '0', '0', '133');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2105', 'Twisting Tower', '1', '40', '0', '12', '1', '4', '135', '5', '1', '0', '1', '0', '135');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2106', 'Battle For Praag', '1', '40', '0', '12', '6', '4', '136', '2', '1', '0', '0', '0', '136');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2107', 'Grovod Caverns', '1', '40', '0', '12', '7', '4', '137', '5', '1', '0', '0', '0', '137');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2108', 'Reikland Factory', '1', '40', '0', '12', '1', '4', '138', '5', '1', '0', '0', '0', '138');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2109', 'Reikland Hills', '1', '40', '0', '12', '1', '4', '134', '5', '1', '0', '0', '0', '134');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2110', 'The Inevitable City', '1', '40', '0', '24', '6', '4', '167', '10', '1', '0', '1', '0', '167');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2111', 'Altdorf', '1', '40', '0', '24', '6', '4', '168', '10', '1', '0', '1', '0', '168');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2123', 'The Eternal Citadel', '1', '40', '0', '12', '7', '4', '172', '5', '1', '0', '0', '0', '172');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2136', 'College of Corruption', '1', '40', '0', '12', '2', '4', '411', '5', '1', '0', '1', '0', '411');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2200', 'Khaine\'s Embrace', '1', '40', '0', '12', '8', '4', '230', '5', '1', '0', '0', '0', '230');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2201', 'Phoenix Gate', '1', '40', '0', '12', '10', '4', '231', '2', '1', '0', '0', '0', '231');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2202', 'Tor Anroc', '1', '40', '0', '12', '2', '4', '232', '10', '1', '0', '0', '0', '232');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2203', 'Lost Temple of Isha', '1', '40', '0', '12', '1', '4', '236', '2', '1', '0', '0', '0', '236');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2204', 'Serpent\'s Passage', '1', '40', '0', '12', '5', '4', '234', '2', '1', '0', '0', '0', '234');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2205', 'Dragon\'s Bane', '1', '40', '0', '12', '1', '4', '235', '5', '1', '0', '0', '0', '235');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2206', 'Blood of the Black Cairn', '1', '40', '0', '12', '11', '4', '238', '5', '1', '0', '0', '0', '238');
INSERT INTO `scenario_infos` (`ScenarioID`, `Name`, `MinLevel`, `MaxLevel`, `MinPlayers`, `MaxPlayers`, `Type`, `Tier`, `MapID`, `KillPointScore`, `RewardScaler`, `DeferKills`, `Enabled`, `QueueType`, `RegionId`) VALUES ('2207', 'Caledor Woods', '1', '40', '0', '12', '1', '4', '237', '2', '1', '0', '0', '0', '237');
