DROP TABLE IF EXISTS `creature_smart_abilities`;

CREATE TABLE `creature_smart_abilities` (
  `Guid` int(11) NOT NULL AUTO_INCREMENT,
  `CreatureTypeId` int(11) NOT NULL,
  `CreatureSubTypeId` int(11) NOT NULL,
  `CreatureTypeDescription` text NOT NULL,
  `SpellCastName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `SpellCastSpeech` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `SpellCondition` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `SpellCastExecution` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `SpellExecuteChance` int(11) NOT NULL,
  `SpellCastCoolDown` int(11) NOT NULL,
  `SpellCastSound` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  PRIMARY KEY (`Guid`,`CreatureTypeId`,`CreatureSubTypeId`)
) ENGINE=InnoDB AUTO_INCREMENT=92 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Data for the table `creature_smart_abilities` */

LOCK TABLES `creature_smart_abilities` WRITE;

insert  into `creature_smart_abilities`(`Guid`,`CreatureTypeId`,`CreatureSubTypeId`,`CreatureTypeDescription`,`SpellCastName`,`SpellCastSpeech`,`SpellCondition`,`SpellCastExecution`,`SpellExecuteChance`,`SpellCastCoolDown`,`SpellCastSound`) values 
(1,1,1,'ANIMALS_BEASTS_BASILISK','CorrosiveVomit',NULL,'PlayerInMeleeRange','CorrosiveVomit',35,60,NULL),
(2,1,1,'ANIMALS_BEASTS_BASILISK','InfectiousBite','Crack....crack...','PlayerInMeleeRange','InfectiousBite',75,30,NULL),
(3,1,2,'ANIMALS_BEASTS_BEAR','LowBlow',NULL,'PlayerInMeleeRange','LowBlow',35,60,NULL),
(4,1,2,'ANIMALS_BEASTS_BEAR','Shred','Roarrr...','PlayerInMeleeRange','Shred',65,25,NULL),
(5,1,3,'ANIMALS_BEASTS_BOAR','LegTear',NULL,'PlayerInMeleeRange','LegTear',70,60,NULL),
(6,1,3,'ANIMALS_BEASTS_BOAR','Bite','Phrrr..phrr..','PlayerInMeleeRange','Gore',100,20,NULL),
(7,1,4,'ANIMALS_BEASTS_GIANT_BAT','Bite',NULL,'PlayerInMeleeRange','Bite',100,5,NULL),
(8,1,4,'ANIMALS_BEASTS_GIANT_BAT','BatScreech','Scccreeach...','PlayerInMeleeRange','BatScreech',100,10,NULL),
(9,1,5,'ANIMALS_BEASTS_GREAT_CAT','LegTear','Frrr....frrrr....','PlayerInMeleeRange','LegTear',70,60,NULL),
(10,1,5,'ANIMALS_BEASTS_GREAT_CAT','Shred',NULL,'PlayerInMeleeRange','Shred',65,25,NULL),
(11,1,6,'ANIMALS_BEASTS_HOUND','LegTear',NULL,'PlayerInMeleeRange','LegTear',70,60,NULL),
(12,1,6,'ANIMALS_BEASTS_HOUND','Maul',NULL,'PlayerInMeleeRange','Maul',100,25,NULL),
(13,1,7,'ANIMALS_BEASTS_RHINOX','Charge',NULL,'PlayersWithinRange','Charge',55,30,NULL),
(14,1,7,'ANIMALS_BEASTS_RHINOX','CripplingBlow',NULL,'PlayerInMeleeRange','CripplingBlow',70,60,NULL),
(15,1,8,'ANIMALS_BEASTS_WOLF','LegTear',NULL,'PlayerInMeleeRange','LegTear',70,60,NULL),
(16,1,8,'ANIMALS_BEASTS_WOLF','Bite','Grrrrrr....grrr...','PlayerInMeleeRange','Bite',100,20,NULL),
(17,3,19,'ANIMALS_INSECTS_ARACHNIDS_GIANT_SCORPION','InfectiousBite','Scrach...scrach...','PlayerInMeleeRange','InfectiousBite',75,60,NULL),
(18,3,19,'ANIMALS_INSECTS_ARACHNIDS_GIANT_SCORPION','EnvenomedStinger',NULL,'PlayerInMeleeRange','EnvenomedStinger',35,60,NULL),
(19,3,20,'ANIMALS_INSECTS_ARACHNIDS_GIANT_SPIDER','WhitefireWebBolt',NULL,'PlayersWithinRange','WhitefireWebBolt',70,50,NULL),
(20,3,20,'ANIMALS_INSECTS_ARACHNIDS_GIANT_SPIDER','EnvenomedStinger','Shrech...shrech....','PlayerInMeleeRange','EnvenomedStinger',35,60,NULL),
(21,3,21,'ANIMALS_INSECTS_ARACHNIDS_TOMB_SWARM','InfectiousBite',NULL,'PlayerInMeleeRange','InfectiousBite',75,60,NULL),
(22,3,21,'ANIMALS_INSECTS_ARACHNIDS_TOMB_SWARM','CripplingThorns',NULL,'PlayerInMeleeRange','CripplingThorns',35,30,NULL),
(23,5,29,'ANIMALS_REPTILES_COLD_ONE','Bite',NULL,'PlayerInMeleeRange','Bite',75,20,NULL),
(24,5,29,'ANIMALS_REPTILES_COLD_ONE','CripplingBlow',NULL,'PlayerInMeleeRange','CripplingBlow',45,60,NULL),
(25,5,30,'ANIMALS_REPTILES_GIANT_LIZARD','CorrosiveVomit',NULL,'PlayerInMeleeRange','CorrosiveVomit',35,60,NULL),
(26,5,30,'ANIMALS_REPTILES_GIANT_LIZARD','InfectiousBite','Shhhhmesh....shhhmesh...','PlayerInMeleeRange','InfectiousBite',75,30,NULL),
(27,6,31,'DAEMONS_KHORNE_BLOODBEAST','BloodStomp',NULL,'PlayerInMeleeRange','BloodStomp',35,60,NULL),
(28,6,31,'DAEMONS_KHORNE_BLOODBEAST','BoneyStrike',NULL,'PlayerInMeleeRange','BoneyStrike',75,30,NULL),
(29,6,32,'DAEMONS_KHORNE_BLOODLETTER','Wotarmor',NULL,'PlayerInMeleeRange','Wotarmor',35,60,NULL),
(30,6,32,'DAEMONS_KHORNE_BLOODLETTER','Slice',NULL,'PlayerInMeleeRange','Slice',65,30,NULL),
(31,6,32,'DAEMONS_KHORNE_BLOODLETTER','CripplingBlow',NULL,'PlayerInMeleeRange','CripplingBlow',55,45,NULL),
(32,6,34,'DAEMONS_KHORNE_FLESH_HOUND','Bite','Auuu...uuu...','PlayerInMeleeRange','Bite',75,60,NULL),
(33,6,34,'DAEMONS_KHORNE_FLESH_HOUND','FeralBite',NULL,'PlayerInMeleeRange','FeralBite',15,60,NULL),
(34,6,34,'DAEMONS_KHORNE_FLESH_HOUND','InfectiousBite',NULL,'PlayerInMeleeRange','InfectiousBite',55,60,NULL),
(35,7,36,'DAEMONS_NURGLE_GREAT_UNCLEAN_ONE','SlimyVomit',NULL,'PlayersWithinRange','SlimyVomit',45,60,NULL),
(36,7,37,'DAEMONS_NURGLE_NURGLING','PoisonSpit','Nurgsh...nurgshh...','PlayerInMeleeRange','PoisonSpit',35,60,NULL),
(37,7,37,'DAEMONS_NURGLE_NURGLING','InfectiousBite',NULL,'PlayerInMeleeRange','InfectiousBite',75,30,NULL),
(38,7,38,'DAEMONS_NURGLE_PLAGUEBEARER','CorrosiveVomit',NULL,'PlayerInMeleeRange','CorrosiveVomit',35,60,NULL),
(39,7,38,'DAEMONS_NURGLE_PLAGUEBEARER','PoisonSpit','Arrhhhh...rhhh....','PlayerInMeleeRange','PoisonSpit',50,45,NULL),
(41,7,39,'DAEMONS_NURGLE_PLAGUEBEAST','CripplingBlow',NULL,'PlayerInMeleeRange','CripplingBlow',35,60,NULL),
(42,7,39,'DAEMONS_NURGLE_PLAGUEBEAST','LowBlow','Shsmesh...','PlayerInMeleeRange','LowBlow',55,60,NULL),
(43,7,39,'DAEMONS_NURGLE_PLAGUEBEAST','GroundRumble',NULL,'PlayerInMeleeRange','GroundRumble',15,80,NULL),
(44,7,40,'DAEMONS_NURGLE_SLIME_HOUND','CripplingBlow','Phlushh...phlush..','PlayerInMeleeRange','CripplingBlow',55,45,NULL),
(45,7,40,'DAEMONS_NURGLE_SLIME_HOUND','CorrosiveVomit',NULL,'PlayerInMeleeRange','CorrosiveVomit',35,60,NULL),
(46,7,40,'DAEMONS_NURGLE_SLIME_HOUND','InfectiousBite',NULL,'PlayerInMeleeRange','InfectiousBite',55,60,NULL),
(47,7,40,'DAEMONS_NURGLE_SLIME_HOUND','Bite','Phesh..phesh...','PlayerInMeleeRange','Bite',75,60,NULL),
(48,8,41,'DAEMONS_SLAANESH_DAEMONETTE','LegTear','Shew...shew...','PlayerInMeleeRange','LegTear',55,60,NULL),
(49,8,41,'DAEMONS_SLAANESH_DAEMONETTE','Shred',NULL,'PlayerInMeleeRange','Shred',45,45,NULL),
(50,8,41,'DAEMONS_SLAANESH_DAEMONETTE','GutRipper',NULL,'PlayerInMeleeRange','GutRipper',65,55,NULL),
(51,9,45,'DAEMONS_TZEENTCH_FLAMER','FlamesofChange',NULL,'PlayersWithinRange','FlamesofChange',65,55,NULL),
(52,9,45,'DAEMONS_TZEENTCH_FLAMER','FlameofTzeentch','Fffflashsh.....fflaaahsh...','PlayersWithinRange','FlameofTzeentch',45,50,NULL),
(53,9,45,'DAEMONS_TZEENTCH_FLAMER','DaemonicFire',NULL,'PlayersWithinRange','DaemonicFire',55,60,NULL),
(54,9,46,'DAEMONS_TZEENTCH_HORROR','DaemonicConsumption',NULL,'PlayerInMeleeRange','DaemonicConsumption',100,15,NULL),
(55,9,46,'DAEMONS_TZEENTCH_HORROR','WarpingEnergy','Shrapp...shrapp...','PlayerInMeleeRange','WarpingEnergy',100,35,NULL),
(56,9,46,'DAEMONS_TZEENTCH_HORROR','DaemonicFire',NULL,'PlayerInMeleeRange','DaemonicFire',100,20,NULL),
(57,9,48,'DAEMONS_TZEENTCH_SCREAMER','FlamesofChange','Screechh...screech...','PlayerInMeleeRange','FlamesofChange',45,60,NULL),
(58,9,48,'DAEMONS_TZEENTCH_SCREAMER','DaemonicFire',NULL,'PlayerInMeleeRange','DaemonicFire',65,45,NULL),
(59,10,50,'DAEMONS_UNMARKED_DAEMONS_CHAOS_FURY','GutRipper',NULL,'PlayerInMeleeRange','GutRipper',60,30,NULL),
(60,10,50,'DAEMONS_UNMARKED_DAEMONS_CHAOS_FURY','FeralBite',NULL,'PlayerInMeleeRange','FeralBite',45,45,NULL),
(61,10,51,'DAEMONS_UNMARKED_DAEMONS_CHAOS_HOUND','Bite',NULL,'PlayerInMeleeRange','Bite',75,20,NULL),
(62,10,51,'DAEMONS_UNMARKED_DAEMONS_CHAOS_HOUND','FeralBite',NULL,'PlayerInMeleeRange','FeralBite',15,60,NULL),
(63,10,51,'DAEMONS_UNMARKED_DAEMONS_CHAOS_HOUND','InfectiousBite','Whreeck...whreeck...','PlayerInMeleeRange','InfectiousBite',55,60,NULL),
(64,10,52,'DAEMONS_UNMARKED_DAEMONS_CHAOS_SPAWN','LegTear',NULL,'PlayerInMeleeRange','LegTear',55,60,NULL),
(65,10,52,'DAEMONS_UNMARKED_DAEMONS_CHAOS_SPAWN','BloodStomp',NULL,'PlayerInMeleeRange','BloodStomp',45,60,NULL),
(66,10,54,'DAEMONS_UNMARKED_DAEMONS_DAEMONVINE','CorrosiveVomit',NULL,'PlayerInMeleeRange','CorrosiveVomit',35,60,NULL),
(67,10,54,'DAEMONS_UNMARKED_DAEMONS_DAEMONVINE','InfectiousBite',NULL,'PlayerInMeleeRange','InfectiousBite',75,30,NULL),
(68,10,55,'DAEMONS_UNMARKED_DAEMONS_WALKER','CorrosiveVomit',NULL,'PlayerInMeleeRange','CorrosiveVomit',35,60,NULL),
(69,10,55,'DAEMONS_UNMARKED_DAEMONS_WALKER','InfectiousBite','Phhhreshh..pphhhreshh...','PlayerInMeleeRange','InfectiousBite',75,30,NULL),
(70,11,56,'HUMANOIDS_BEASTMEN_BESTIGOR','BloodyClaw',NULL,'PlayerInMeleeRange','BloodyClaw',60,60,NULL),
(71,11,56,'HUMANOIDS_BEASTMEN_BESTIGOR','ViciousSlash',NULL,'PlayerInMeleeRange','ViciousSlash',45,45,NULL),
(72,11,57,'HUMANOIDS_BEASTMEN_BRAY_SHAMAN','CripplingBlow',NULL,'PlayerInMeleeRange','CripplingBlow',55,45,NULL),
(73,11,57,'HUMANOIDS_BEASTMEN_BRAY_SHAMAN','BloodStomp','Kkkroshh...','PlayerInMeleeRange','BloodStomp',55,30,NULL),
(74,11,59,'HUMANOIDS_BEASTMEN_GOR','ViciousSlash',NULL,'PlayerInMeleeRange','ViciousSlash',45,45,NULL),
(75,11,59,'HUMANOIDS_BEASTMEN_GOR','BloodyClaw','Grrrr...gggrrr...','PlayerInMeleeRange','BloodyClaw',60,60,NULL),
(76,11,60,'HUMANOIDS_BEASTMEN_UNGOR','ViciousSlash',NULL,'PlayerInMeleeRange','ViciousSlash',45,45,NULL),
(77,11,60,'HUMANOIDS_BEASTMEN_UNGOR','CripplingBlow',NULL,'PlayerInMeleeRange','CripplingBlow',55,45,NULL),
(78,12,61,'HUMANOIDS_DARK_ELVES_BLACK_GUARD','MurderousWrath','Die! You are patetic!','PlayerInMeleeRange','MurderousWrath',70,45,NULL),
(79,12,61,'HUMANOIDS_DARK_ELVES_BLACK_GUARD','HatefulStrike','Die die diieee!!','PlayerInMeleeRange','HatefulStrike',55,45,NULL),
(80,12,61,'HUMANOIDS_DARK_ELVES_BLACK_GUARD','SpitefulSlam',NULL,'PlayerInMeleeRange','SpitefulSlam',15,60,NULL),
(81,12,61,'HUMANOIDS_DARK_ELVES_BLACK_GUARD','AwayCretins',NULL,'PlayerInMeleeRange','AwayCretins',30,55,NULL),
(82,13,67,'HUMANOIDS_DWARFS_ENGINEER','GunTurret','Wait a second...','SeventyFivePercentHealth','GunTurret',100,100,NULL),
(83,13,67,'HUMANOIDS_DWARFS_ENGINEER ','MinorPotionofHealing','Where are my heal bottle..?','ThirtyPercentHealth','MinorPotionofHealing',100,50,NULL),
(84,13,70,'HUMANOIDS_DWARFS_RUNEPRIEST ','RuneofShielding','Runes protect me!','PlayersWithinRange','RuneofShielding',100,45,NULL),
(85,13,70,'HUMANOIDS_DWARFS_RUNEPRIEST ','RuneofStriking',NULL,'PlayersWithinRange','RuneofStriking',100,0,NULL),
(86,16,92,'HUMANOIDS_HUMANS_GHOUL','ClawSweep','Wheeeeeshhh....wheeeshh...','PlayerInMeleeRange','ClawSweep',100,15,NULL),
(87,16,92,'HUMANOIDS_HUMANS_GHOUL','FoulVomit','Kkkkilll youuu...kkill...','PlayerInMeleeRange','FoulVomit',100,35,NULL),
(88,18,106,'HUMANOIDS_SKAVEN_SKAVEN','ScytheGash','Now ggget it...get it...','PlayerInMeleeRange','ScytheGash',100,15,NULL),
(89,18,106,'HUMANOIDS_SKAVEN_SKAVEN','SimpleStrike','Shhhh...kill..kill you...','PlayerInMeleeRange','SimpleStrike',70,25,NULL);