INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `SecondaryValue`, `InvokeOn`, `Target`) VALUES ('5092', 'Blood Stomp', '0', '0', 'ApplyCC', '32', '1', '5', 'Host');
INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `InvokeOn`, `Target`, `BuffLine`) VALUES ('5063', 'Blood Roots', '0', '0', 'Root', '5', 'Host', '1');
INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `InvokeOn`, `Target`) VALUES ('5063', 'Blood Roots', '1', '0', 'DamageOverTime', '5', 'Host');
INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `InvokeOn`, `Target`, `BuffLine`) VALUES ('5066', 'Bloodpulse', '0', '0', 'DamageOverTime', '5', 'Host', '1');
INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `InvokeOn`, `Target`, `BuffLine`) VALUES ('13307', 'Charge', '0', '0', 'ModifySpeed', '200', '5', 'Host', '1');
INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `SecondaryValue`, `InvokeOn`, `Target`, `BuffLine`) VALUES ('13307', 'Charge', '0', '1', 'ApplyCC', '16', '1', '5', 'Host', '2');
INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `SecondaryValue`, `InvokeOn`, `Target`, `BuffLine`) VALUES ('5809', 'Scent of Blood', '0', '0', 'ModifyStat', '67', '100', '5', 'Host', '1');

INSERT INTO `war_world`.`ability_commands` (`Entry`, `AbilityName`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `Target`, `EffectRadius`, `MaxTargets`) VALUES ('5063', 'Blood Roots', '0', '0', 'InvokeBuff', '5063', 'Enemy', '255', '6');
INSERT INTO `war_world`.`ability_commands` (`Entry`, `AbilityName`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `Target`, `EffectRadius`, `MaxTargets`) VALUES ('5066', 'Bloodpulse', '0', '0', 'InvokeBuff', '5066', 'Enemy', '55', '6');
INSERT INTO `war_world`.`ability_commands` (`Entry`, `AbilityName`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `Target`) VALUES ('5551', 'Bloodscent Aura', '0', '0', 'InvokeAura', '5551', 'Host');

INSERT INTO `war_world`.`ability_damage_heals` (`Entry`, `Index`, `Name`, `MinDamage`, `MaxDamage`, `DamageVariance`, `DamageType`, `ParentCommandID`, `ParentCommandSequence`, `CastTimeDamageMult`, `WeaponDamageFrom`, `WeaponDamageScale`, `NoCrits`, `Undefendable`, `OverrideDefenseEvent`, `StatUsed`, `StatDamageScale`, `ResourceBuild`, `HatredScale`, `HealHatredScale`, `PriStatMultiplier`) VALUES ('5063', '0', 'Blood Roots', '1000', '2000', '0', 'Physical', '0', '0', '1', '1', '1', '0', '1', '1', '0', '1', '0', '1', '1', '1');
INSERT INTO `war_world`.`ability_damage_heals` (`Entry`, `Index`, `Name`, `MinDamage`, `MaxDamage`, `DamageType`, `ParentCommandID`, `ParentCommandSequence`, `StatDamageScale`, `HatredScale`, `HealHatredScale`) VALUES ('5066', '0', 'Bloodpulse', '4000', '8000', 'Spiritual', '0', '0', '1', '1', '1');
INSERT INTO `war_world`.`ability_damage_heals` (`Entry`, `Index`, `Name`, `MinDamage`, `MaxDamage`, `DamageType`, `ParentCommandID`, `ParentCommandSequence`, `StatDamageScale`, `HatredScale`, `HealHatredScale`) VALUES ('5551', '0', 'Bloodscent Aura', '0', '0', 'Spiritual', '0', '0', '1', '1', '1');

INSERT INTO `war_world`.`buff_infos` (`Entry`, `Name`, `MaxStack`, `Duration`, `Silent`) VALUES ('5063', 'Blood Roots', '1', '10', '1');
INSERT INTO `war_world`.`buff_infos` (`Entry`, `Name`, `MaxCopies`, `MaxStack`, `Duration`, `Silent`) VALUES ('13307', 'Charge', '1', '1', '5', '1');
INSERT INTO `war_world`.`buff_infos` (`Entry`, `Name`, `MaxStack`, `Duration`, `Interval`, `CanRefresh`, `Silent`) VALUES ('5809', 'Scent of Blood', '1', '15', '1000', '1', '1');
INSERT INTO `war_world`.`buff_infos` (`Entry`, `Name`, `MaxCopies`, `MaxStack`, `Duration`, `Silent`) VALUES ('5066', 'Bloodpulse', '1', '1', '10', '1');
INSERT INTO `war_world`.`buff_infos` (`Entry`, `Name`, `AuraPropagation`, `MaxStack`, `PersistsOnDeath`) VALUES ('5551', 'Bloodscent Aura', 'Group', '1', '1');

INSERT INTO `war_world`.`abilities` (`Entry`, `CareerLine`, `Name`, `MinRange`, `Range`, `CastTime`, `Cooldown`, `ApCost`, `SpecialCost`, `MoveCast`, `EffectID`, `Specline`, `WeaponNeeded`, `AffectsDead`, `IgnoreGlobalCooldown`, `IgnoreOwnModifiers`, `MinimumRank`, `MinimumRenown`, `IconId`, `abilityID`) VALUES ('5066', '0', 'Bloodpulse', '0', '333', '0', '20', '0', '0', '1', '2112', 'NPC', '0', '0', '1', '1', '0', '0', '5066', '5066');
INSERT INTO `war_world`.`abilities` (`Entry`, `CareerLine`, `Name`, `Cooldown`, `AbilityType`, `Specline`, `IgnoreGlobalCooldown`, `MinimumRank`, `MinimumRenown`, `IconId`, `Category`, `Flags`, `PointCost`, `CashCost`) VALUES ('5551', '0', 'Bloodscent Aura', '15', '3', 'NPC', '1', '0', '0', '5551', '0', '0', '0', '0');
INSERT INTO `war_world`.`abilities` (`Entry`, `CareerLine`, `Name`, `Range`, `CastTime`, `Cooldown`, `ApCost`, `EffectID`, `AbilityType`, `Specline`, `WeaponNeeded`, `MinimumRank`, `MinimumRenown`, `IconId`, `Category`, `Flags`, `PointCost`, `CashCost`, `AIRange`) VALUES ('13713', '0', 'Thar\'lgnan\'s Hurl', '10', '0', '25', '0', '13713', '1', 'NPC', '0', '0', '0', '13713', '0', '0', '0', '0', '10');
INSERT INTO `war_world`.`abilities` (`Entry`, `CareerLine`, `Name`, `CastTime`, `Cooldown`, `ApCost`, `SpecialCost`, `MoveCast`, `EffectID`, `Specline`, `AffectsDead`, `IgnoreGlobalCooldown`, `MinimumRank`, `MinimumRenown`, `IconId`, `Category`, `Flags`, `PointCost`, `CashCost`) VALUES ('13307', '0', 'Charge', '0', '0', '0', '0', '1', '13307', 'NPC', '0', '0', '0', '0', '13307', '0', '0', '0', '0');
INSERT INTO `war_world`.`abilities` (`Entry`, `CareerLine`, `Name`, `Range`, `CastTime`, `Cooldown`, `ApCost`, `SpecialCost`, `CastAngle`, `Specline`, `WeaponNeeded`, `MinimumRank`, `MinimumRenown`, `IconId`, `Category`, `Flags`, `PointCost`, `CashCost`, `AIRange`) VALUES ('5809', '0', 'Scent of Blood', '10', '0', '0', '0', '0', '0', 'NPC', '0', '0', '0', '5809', '0', '0', '0', '0', '10');

INSERT INTO `war_world`.`ability_commands` (`Entry`, `AbilityName`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `Target`) VALUES ('13713', 'Thar\'lgnan\'s Hurl', '0', '0', 'PuntEnemy', '13713', 'Enemy');
INSERT INTO `war_world`.`ability_commands` (`Entry`, `AbilityName`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `Target`) VALUES ('5809', 'Scent of Blood', '0', '0', 'InvokeBuff', '5809', 'Enemy');
INSERT INTO `war_world`.`ability_commands` (`Entry`, `AbilityName`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `Target`) VALUES ('13307', 'Charge', '0', '0', 'InvokeBuff', '13307', 'Caster');

INSERT INTO `war_world`.`ability_knockback_info` (`Entry`, `Id`, `Angle`, `Power`, `GravMultiplier`) VALUES ('13713', '0', '72', '600', '2');

INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `SecondaryValue`, `InvokeOn`, `Target`, `BuffLine`, `NoAutoUse`) VALUES ('5551', 'Bloodscent Aura', '0', '0', 'ModifyStat', '67', '100', '5', 'Host', '3', '1');

INSERT INTO `war_world`.`creature_abilities` (`ProtoEntry`, `AbilityId`, `Cooldown`, `creature_abilities_ID`, `Text`, `TimeStart`, `ActivateAtHealthPercent`, `DisableAtHealthPercent`, `AbilityCycle`, `Active`, `RandomTarget`) VALUES ('48112', '5066', '20', '1642001', 'Bloodpulse', '0', '100', '0', '1', '1', '1');
INSERT INTO `war_world`.`creature_abilities` (`ProtoEntry`, `AbilityId`, `Cooldown`, `creature_abilities_ID`, `Text`, `TimeStart`, `ActivateAtHealthPercent`, `DisableAtHealthPercent`, `AbilityCycle`, `Active`, `ActivateOnCombatStart`, `RandomTarget`, `TargetFocus`) VALUES ('48112', '5551', '15', '1642002', 'Bloodscent', '0', '100', '0', '1', '1', '0', '1', '1');
INSERT INTO `war_world`.`creature_abilities` (`ProtoEntry`, `AbilityId`, `Cooldown`, `creature_abilities_ID`, `Text`, `TimeStart`, `ActivateAtHealthPercent`, `DisableAtHealthPercent`, `AbilityCycle`, `Active`, `ActivateOnCombatStart`, `RandomTarget`, `TargetFocus`) VALUES ('45088', '5809', '0', '1600000', 'Scent of Blood', '0', '100', '0', '1', '1', '1', '1', '0');
INSERT INTO `war_world`.`creature_abilities` (`ProtoEntry`, `AbilityId`, `Cooldown`, `creature_abilities_ID`, `Text`, `TimeStart`, `ActivateAtHealthPercent`, `DisableAtHealthPercent`, `AbilityCycle`, `Active`, `ActivateOnCombatStart`, `RandomTarget`, `TargetFocus`) VALUES ('45084', '13713', '25', '1631004', 'Thar\'lgnan\'s Hurl', '0', '100', '0', '1', '1', '0', '1', '0');
INSERT INTO `war_world`.`creature_abilities` (`ProtoEntry`, `AbilityId`, `Cooldown`, `creature_abilities_ID`, `Text`, `TimeStart`, `ActivateAtHealthPercent`, `DisableAtHealthPercent`, `AbilityCycle`, `Active`, `ActivateOnCombatStart`, `RandomTarget`, `TargetFocus`) VALUES ('45084', '13307', '0', '1631005', 'Charge', '0', '100', '0', '1', '1', '0', '1', '0');

UPDATE `war_world`.`creature_abilities` SET `ActivateOnCombatStart` = '0' WHERE (`creature_abilities_ID` = '1600000');
UPDATE `war_world`.`creature_abilities` SET `Text` = '' WHERE (`creature_abilities_ID` = '1600000');

UPDATE `war_world`.`ability_commands` SET `PrimaryValue` = NULL WHERE (`Entry` = '13713') and (`CommandID` = '0') and (`CommandSequence` = '0');
UPDATE `war_world`.`buff_infos` SET `MaxCopies` = '1' WHERE (`Entry` = '5809');