using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace FrameWork.NetWork.SourceGenerators
{
    [Generator]
    public class PacketSerializerGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Find all classes marked with [PacketSerializerContext]
            var contextClasses = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax cls && cls.AttributeLists.Count > 0,
                    transform: static (ctx, _) => GetContextClassOrNull(ctx))
                .Where(static m => m is not null);

            // Combine with compilation
            var compilationAndContexts = context.CompilationProvider.Combine(contextClasses.Collect());

            // Generate source for each context
            context.RegisterSourceOutput(compilationAndContexts, static (spc, source) => Execute(source.Left, source.Right!, spc));
        }

        private static ClassDeclarationSyntax? GetContextClassOrNull(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;

            // Must be partial
            if (!classDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword))
                return null;

            // Check for [PacketSerializerContext] attribute
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration);
            if (symbol == null)
                return null;

            var hasContextAttribute = symbol.GetAttributes()
                .Any(a => a.AttributeClass?.Name == "PacketSerializerContextAttribute" &&
                         a.AttributeClass?.ContainingNamespace?.ToDisplayString() == "FrameWork.NetWork.V4");

            return hasContextAttribute ? classDeclaration : null;
        }

        private static void Execute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax?> contexts, SourceProductionContext context)
        {
            if (contexts.IsDefaultOrEmpty)
                return;

            foreach (var contextDeclaration in contexts)
            {
                if (contextDeclaration == null)
                    continue;

                var semanticModel = compilation.GetSemanticModel(contextDeclaration.SyntaxTree);
                var contextSymbol = semanticModel.GetDeclaredSymbol(contextDeclaration);
                if (contextSymbol == null)
                    continue;

                // Get types from the [PacketSerializerContext(typeof(Type1), typeof(Type2), ...)] attribute
                var contextAttribute = contextSymbol.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name == "PacketSerializerContextAttribute");

                if (contextAttribute == null || contextAttribute.ConstructorArguments.IsEmpty)
                    continue;

                var typesToSerialize = new List<INamedTypeSymbol>();

                // The attribute constructor takes params Type[] types
                var typesArg = contextAttribute.ConstructorArguments[0];
                if (typesArg.Kind == TypedConstantKind.Array)
                {
                    foreach (var typeConstant in typesArg.Values)
                    {
                        if (typeConstant.Value is INamedTypeSymbol typeSymbol)
                            typesToSerialize.Add(typeSymbol);
                    }
                }

                if (typesToSerialize.Count > 0)
                {
                    var source = GenerateSource(contextSymbol, typesToSerialize);
                    context.AddSource($"{contextSymbol.Name}_Generated.g.cs", source);
                }
            }
        }

        private static string GenerateSource(INamedTypeSymbol contextSymbol, List<INamedTypeSymbol> types)
        {
            var namespaceName = contextSymbol.ContainingNamespace?.ToDisplayString();
            var className = contextSymbol.Name;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Buffers;");
            sb.AppendLine("using FrameWork.NetWork.V4;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            // Generate partial class implementing IPacketSerializerContext
            sb.AppendLine($"    public partial class {className} : IPacketSerializerContext");
            sb.AppendLine("    {");
            
            // Generate TryDeserialize method
            sb.AppendLine("        public bool TryDeserialize(Type type, ReadOnlySpan<byte> buffer, out object? result)");
            sb.AppendLine("        {");
            sb.AppendLine("            result = null;");
            sb.AppendLine();

            foreach (var type in types)
            {
                var fullTypeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"            if (type == typeof({fullTypeName}))");
                sb.AppendLine("            {");
                sb.AppendLine($"                result = Deserialize{type.Name}(buffer);");
                sb.AppendLine("                return true;");
                sb.AppendLine("            }");
                sb.AppendLine();
            }

            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Generate TrySerialize method
            sb.AppendLine("        public bool TrySerialize(object value, IBufferWriter<byte> writer)");
            sb.AppendLine("        {");

            foreach (var type in types)
            {
                var fullTypeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"            if (value is {fullTypeName} val{type.Name})");
                sb.AppendLine("            {");
                sb.AppendLine($"                Serialize{type.Name}(val{type.Name}, writer);");
                sb.AppendLine("                return true;");
                sb.AppendLine("            }");
                sb.AppendLine();
            }

            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Generate type-specific Deserialize methods
            foreach (var type in types)
            {
                GenerateDeserializeMethod(sb, type);
                sb.AppendLine();
            }

            // Generate type-specific Serialize methods
            foreach (var type in types)
            {
                GenerateSerializeMethod(sb, type);
                sb.AppendLine();
            }

            // SpanReader and SpanWriter are internal in FrameWork.NetWork.V4.BinaryPacketSerializer
            // and will be used by the generated code

            sb.AppendLine("    }");

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static void GenerateDeserializeMethod(StringBuilder sb, INamedTypeSymbol type)
        {
            var fullTypeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"        private {fullTypeName} Deserialize{type.Name}(ReadOnlySpan<byte> buffer)");
            sb.AppendLine("        {");
            sb.AppendLine("            var reader = new BinaryPacketSerializer.SpanReader(buffer);");
            sb.AppendLine();

            var properties = type.GetMembers().OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public && p.SetMethod != null)
                .ToList();

            // Use object initializer to handle required properties
            sb.AppendLine($"            return new {fullTypeName}");
            sb.AppendLine("            {");
            
            for (int i = 0; i < properties.Count; i++)
            {
                var prop = properties[i];
                var propType = prop.Type;
                var isNullable = propType.NullableAnnotation == NullableAnnotation.Annotated;
                var isLast = i == properties.Count - 1;

                if (isNullable)
                {
                    sb.AppendLine($"                {prop.Name} = reader.IsAtEnd() ? null : reader.");
                    GenerateReadExpressionInline(sb, propType);
                }
                else
                {
                    sb.Append($"                {prop.Name} = reader.");
                    GenerateReadExpressionInline(sb, propType);
                }

                sb.AppendLine(isLast ? "" : ",");
            }

            sb.AppendLine("            };");
            sb.AppendLine("        }");
        }

        private static void GenerateReadExpressionInline(StringBuilder sb, ITypeSymbol type)
        {
            var underlyingType = type;
            if (type.NullableAnnotation == NullableAnnotation.Annotated && type is INamedTypeSymbol namedType && namedType.IsGenericType)
            {
                underlyingType = namedType.TypeArguments[0];
            }

            var typeName = underlyingType.SpecialType switch
            {
                SpecialType.System_Byte => "ReadByte()",
                SpecialType.System_SByte => "ReadSByte()",
                SpecialType.System_Int16 => "ReadInt16()",
                SpecialType.System_UInt16 => "ReadUInt16()",
                SpecialType.System_Int32 => "ReadInt32()",
                SpecialType.System_UInt32 => "ReadUInt32()",
                SpecialType.System_Int64 => "ReadInt64()",
                SpecialType.System_UInt64 => "ReadUInt64()",
                SpecialType.System_Single => "ReadFloat()",
                SpecialType.System_Double => "ReadDouble()",
                SpecialType.System_Boolean => "(ReadByte() != 0)",
                SpecialType.System_Enum => "ReadEnum()",
                SpecialType.System_String => "ReadString()",
                _ => "null /* unsupported type */"
            };

            sb.Append(typeName);
        }

        private static void GenerateSerializeMethod(StringBuilder sb, INamedTypeSymbol type)
        {
            var fullTypeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"        private void Serialize{type.Name}({fullTypeName} obj, IBufferWriter<byte> buffer)");
            sb.AppendLine("        {");
            sb.AppendLine("            var writer = new BinaryPacketSerializer.SpanWriter(buffer);");
            sb.AppendLine();

            var properties = type.GetMembers().OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public && p.GetMethod != null)
                .ToList();

            foreach (var prop in properties)
            {
                var propType = prop.Type;
                var isNullable = propType.NullableAnnotation == NullableAnnotation.Annotated;

                if (isNullable)
                {
                    sb.AppendLine($"            if (obj.{prop.Name} != null)");
                    sb.AppendLine("            {");
                    sb.Append("    ");
                }

                sb.Append("            writer.");
                GenerateWriteExpression(sb, propType, $"obj.{prop.Name}");
                sb.AppendLine(";");

                if (isNullable)
                {
                    sb.AppendLine("            }");
                }
            }

            sb.AppendLine("        }");
        }

        private static void GenerateWriteExpression(StringBuilder sb, ITypeSymbol type, string valueExpression)
        {
            var underlyingType = type;
            var needsCast = false;
            if (type.NullableAnnotation == NullableAnnotation.Annotated && type is INamedTypeSymbol namedType && namedType.IsGenericType)
            {
                underlyingType = namedType.TypeArguments[0];
                needsCast = true;
            }

            var value = needsCast ? $"{valueExpression}.Value" : valueExpression;

            var methodName = underlyingType.SpecialType switch
            {
                SpecialType.System_Byte => $"WriteByte({value})",
                SpecialType.System_SByte => $"WriteSByte({value})",
                SpecialType.System_Int16 => $"WriteInt16({value})",
                SpecialType.System_UInt16 => $"WriteUInt16({value})",
                SpecialType.System_Int32 => $"WriteInt32({value})",
                SpecialType.System_UInt32 => $"WriteUInt32({value})",
                SpecialType.System_Int64 => $"WriteInt64({value})",
                SpecialType.System_UInt64 => $"WriteUInt64({value})",
                SpecialType.System_Single => $"WriteFloat({value})",
                SpecialType.System_Double => $"WriteDouble({value})",
                SpecialType.System_Boolean => $"WriteByte((byte)({value} ? 1 : 0))",
                SpecialType.System_Enum => $"WriteByte(Convert.ToByte({value}))",
                SpecialType.System_String => $"WriteString({value})",
                _ => "/* unsupported type */"
            };

            sb.Append(methodName);
        }
    }
}
