using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;

namespace ClientDataMatrix.Services
{
    /// <summary>
    /// Writes the inventory of the extracted client: every data file, its shape, its key, and which
    /// columns look like references into other files.
    ///
    /// Meant to be read before starting work on anything, so the first question -- "what does the
    /// client actually say about this?" -- has a cheap answer instead of being a search.
    /// </summary>
    public static class ClientSourceReport
    {
        /// <summary>
        /// Cap on the link table. The analysis produces thousands of numerically valid candidates,
        /// most of them meaningless, and a file nobody scrolls to the end of is worse than a short
        /// one. Ordering is by how surprising the match is, so the head of the list is the part
        /// worth reading.
        /// </summary>
        private const int MaxLinkRows = 400;

        public static string Write(string extractedRoot, string outputRoot)
        {
            var catalog = new ClientSourceCatalog(extractedRoot);
            List<ClientSourceCatalog.ClientSource> sources = catalog.Discover();

            var analyzer = new ClientLinkAnalyzer();
            var tables = new List<ClientSourceCatalog.LoadedTable>();

            foreach (ClientSourceCatalog.ClientSource source in sources)
            {
                ClientSourceCatalog.LoadedTable table = catalog.Load(source);
                tables.Add(table);
                analyzer.Add(table);
            }

            List<ClientLinkAnalyzer.LinkCandidate> links = analyzer.FindCandidates();

            string directory = Path.Combine(outputRoot, "client-sources");
            Directory.CreateDirectory(directory);

            File.WriteAllText(Path.Combine(directory, "client-data-inventory.md"),
                BuildInventory(extractedRoot, tables, analyzer, links), new UTF8Encoding(false));

            File.WriteAllText(Path.Combine(directory, "client-data-links.md"),
                BuildLinks(links), new UTF8Encoding(false));

            return directory;
        }

        private static string BuildInventory(string root, List<ClientSourceCatalog.LoadedTable> tables,
            ClientLinkAnalyzer analyzer, List<ClientLinkAnalyzer.LinkCandidate> links)
        {
            var text = new StringBuilder();

            text.AppendLine("# Client data inventory");
            text.AppendLine();
            text.AppendLine("Every data file in the extracted client, with its shape and key. Generated by");
            text.AppendLine("`ClientDataMatrix report sources`; do not edit by hand.");
            text.AppendLine();
            text.AppendLine("Root: `" + root + "`");
            text.AppendLine();

            int loaded = tables.Count(t => t.Error == null);
            int failed = tables.Count - loaded;
            long rows = tables.Where(t => t.Error == null).Sum(t => (long)t.Rows.Count);

            text.AppendLine("| | |");
            text.AppendLine("| --- | --- |");
            text.AppendLine("| Files discovered | " + tables.Count + " |");
            text.AppendLine("| Read successfully | " + loaded + " |");
            text.AppendLine("| Failed to read | " + failed + " |");
            text.AppendLine("| Data rows | " + rows.ToString("N0", CultureInfo.InvariantCulture) + " |");
            text.AppendLine("| Joinable (unique integer key) | "
                + tables.Count(t => t.HasUniqueIntegerKey && t.Keys.Count > 0)
                    .ToString("N0", CultureInfo.InvariantCulture) + " |");
            text.AppendLine("| Global reference tables searched for links | " + analyzer.TableCount + " |");
            text.AppendLine("| Candidate links | " + links.Count.ToString("N0", CultureInfo.InvariantCulture) + " |");
            text.AppendLine();
            text.AppendLine("A file with a unique integer first column can be joined against; one without cannot,");
            text.AppendLine("and that is stated per file below rather than left to be discovered.");
            text.AppendLine();
            text.AppendLine("Link searching covers `data/gamedata` and `data/strings/english` only -- the tables other");
            text.AppendLine("files actually reference. Including the per-zone and per-asset files as targets produced");
            text.AppendLine("280,761 candidates of pure combinatorial noise, since a texture list keyed 1..40 absorbs any");
            text.AppendLine("small column in the game. Every file is still inventoried below.");
            text.AppendLine();

            foreach (IGrouping<string, ClientSourceCatalog.LoadedTable> family in tables
                         .GroupBy(t => t.Source.Family)
                         .OrderBy(g => g.Key, StringComparer.OrdinalIgnoreCase))
            {
                text.AppendLine("## " + family.Key);
                text.AppendLine();
                text.AppendLine("| File | Format | Rows | Cols | Key | Notes |");
                text.AppendLine("| --- | --- | --- | --- | --- | --- |");

                foreach (ClientSourceCatalog.LoadedTable table in family
                             .OrderBy(t => t.Source.Name, StringComparer.OrdinalIgnoreCase))
                {
                    string notes = table.Error != null
                        ? "**unreadable** -- " + table.Error
                        : BuildNotes(table);

                    text.AppendLine("| `" + table.Source.Name + "` | " + table.Source.Format
                        + " | " + table.Rows.Count.ToString("N0", CultureInfo.InvariantCulture)
                        + " | " + table.ColumnCount
                        + " | " + (table.HasUniqueIntegerKey ? "yes" : "no")
                        + " | " + notes + " |");
                }

                text.AppendLine();
            }

            return text.ToString();
        }

        private static string BuildNotes(ClientSourceCatalog.LoadedTable table)
        {
            var parts = new List<string>();

            if (table.HeaderRows > 0)
                parts.Add(table.HeaderRows + " header row" + (table.HeaderRows == 1 ? "" : "s"));

            if (table.CommentRows > 0)
                parts.Add(table.CommentRows + " comment row" + (table.CommentRows == 1 ? "" : "s") + " dropped");

            if (table.Degraded)
                parts.Add("**degraded read** -- malformed XML, elements counted textually");

            // Say when a key is not clean. A file counted as joinable despite a few repeated or
            // missing ids should show that, so nobody treats the join as exact.
            if (table.DuplicateKeys > 0)
                parts.Add(table.DuplicateKeys + " repeated id" + (table.DuplicateKeys == 1 ? "" : "s"));

            if (table.UnkeyedRows > 0)
                parts.Add(table.UnkeyedRows + " row" + (table.UnkeyedRows == 1 ? "" : "s") + " with no id");

            if (table.Rows.Count == 0)
                parts.Add("empty");

            if (table.Columns.Count > 0)
            {
                // The first few column names say more about a file than any description could.
                string joined = string.Join(", ", table.Columns
                    .Where(c => !string.IsNullOrWhiteSpace(c))
                    .Take(6));

                if (joined.Length > 0)
                    parts.Add("columns: " + joined.Replace("|", "/"));
            }

            return parts.Count == 0 ? "" : string.Join("; ", parts);
        }

        private static string BuildLinks(List<ClientLinkAnalyzer.LinkCandidate> links)
        {
            var text = new StringBuilder();

            text.AppendLine("# Client data links");
            text.AppendLine();
            text.AppendLine("Columns whose values resolve into another file's key. Generated by");
            text.AppendLine("`ClientDataMatrix report sources`; do not edit by hand.");
            text.AppendLine();
            text.AppendLine("## Read this before using the table");
            text.AppendLine();
            text.AppendLine("**These are leads, not conclusions**, and the numbers alone cannot tell you which.");
            text.AppendLine();
            text.AppendLine("Most of these files number their rows from 1 with no gaps. Any column of numbers that");
            text.AppendLine("falls inside such a range resolves into it completely, whether or not it means to, so a");
            text.AppendLine("100% rate against a dense target is worth nothing on its own. That is what the **target");
            text.AppendLine("density** column is for: at 100% the target is a contiguous run of ids and the match is");
            text.AppendLine("free; the lower it goes, the more the match had to earn.");
            text.AppendLine();
            text.AppendLine("Rows are ordered by how surprising the match is rather than by rate, so the top of the");
            text.AppendLine("table is the part worth reading.");
            text.AppendLine();
            text.AppendLine("The **sample** column is what actually settles it. Nothing about 88,676 item rows");
            text.AppendLine("resolving into `objects.csv` proves `ModelId` means art -- what proves it is that 8334 is");
            text.AppendLine("named `tk_soultalisman_intelligence` and the item carrying it grants Intelligence. Read");
            text.AppendLine("the names, not the percentages.");
            text.AppendLine();
            text.AppendLine("And the standing warning: `data/gamedata/abilities.csv` agrees with the client's real");
            text.AppendLine("ability ids on 13 of 3,115 while looking entirely plausible by these measures. Joining on");
            text.AppendLine("it is what filled `mythic_src_abilities` with another ability's names and effect ids.");
            text.AppendLine();
            text.AppendLine("Thresholds: at least " + ClientLinkAnalyzer.MinimumDistinctValues
                + " distinct values, at least "
                + (ClientLinkAnalyzer.MinimumResolveRate * 100).ToString("0", CultureInfo.InvariantCulture)
                + "% resolving. Column 0 is never treated as a source, being the row id in these files.");
            text.AppendLine();

            text.AppendLine("## Candidates");
            text.AppendLine();
            text.AppendLine("| From | Column | To | Distinct | Rate | Target density | Sample |");
            text.AppendLine("| --- | --- | --- | --- | --- | --- | --- |");

            int shown = 0;
            foreach (ClientLinkAnalyzer.LinkCandidate link in links)
            {
                if (shown >= MaxLinkRows)
                    break;

                ++shown;

                text.AppendLine("| `" + link.FromTable + "` | `" + link.FromColumn
                    + "` [" + link.FromColumnIndex + "] | `" + link.ToTable
                    + "` | " + link.DistinctValues.ToString("N0", CultureInfo.InvariantCulture)
                    + " | " + (link.ResolveRate * 100).ToString("0.0", CultureInfo.InvariantCulture) + "%"
                    + " | " + (link.TargetDensity * 100).ToString("0", CultureInfo.InvariantCulture) + "%"
                    + " | " + (link.Samples.Count == 0
                        ? ""
                        : string.Join("; ", link.Samples).Replace("|", "/")) + " |");
            }

            if (links.Count == 0)
                text.AppendLine("| _none above the thresholds_ | | | | | | |");

            text.AppendLine();

            if (links.Count > shown)
            {
                text.AppendLine("_" + (links.Count - shown).ToString("N0", CultureInfo.InvariantCulture)
                    + " further candidates below this cut, all less specific than those above._");
                text.AppendLine();
            }

            return text.ToString();
        }
    }
}
