using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using FrameWork.NetWork.SourceGenerators;

namespace Tests.RpcSourceGenerator;

public class RpcSourceGeneratorSnapshotTests
{
    private static readonly string ClientBaseCode = @"
namespace FrameWork.NetWork.V4
{
    public abstract class Client
    {
        protected abstract void ProcessPacket(byte opcode, ReadOnlySpan<byte> payload);
        protected void SendResponse<T>(byte opcode, T response) { }
        protected void OnUnknownOpcode(byte opcode) { }
        protected void OnHandlerError(byte opcode, Exception ex) { }
    }
    
    [System.AttributeUsage(System.AttributeTargets.Method)]
    public class RpcAttribute : System.Attribute
    {
        public byte Opcode { get; }
        public byte? ResponseOpcode { get; }
        public RpcAttribute(byte opcode) { Opcode = opcode; }
        public RpcAttribute(byte opcode, byte responseOpcode) { Opcode = opcode; ResponseOpcode = responseOpcode; }
    }
    
    public interface IPacketSerializer
    {
        void Serialize<T>(System.Buffers.IBufferWriter<byte> writer, T value);
        T Deserialize<T>(ReadOnlySpan<byte> data);
    }
}";

    [Fact]
    public Task GeneratesCompleteRpcHandler()
    {
        var source = @"
using System;
using System.Threading.Tasks;
using FrameWork.NetWork.V4;

namespace TestNamespace
{
    public class PingRequest { }
    public class PingResponse { }
    public class LoginRequest { }
    public class LoginResponse { }
    public class NotifyRequest { }
    
    public partial class GameClient : Client
    {
        private IPacketSerializer Serializer { get; }
        
        [Rpc(0x01)]
        public void HandlePing()
        {
            // Ping handler
        }

        [Rpc(0x10, 0x11)]
        public LoginResponse HandleLogin(LoginRequest request)
        {
            return new LoginResponse();
        }

        [Rpc(0x20, 0x21)]
        public async Task<PingResponse> HandlePingAsync(PingRequest request)
        {
            await Task.Delay(10);
            return new PingResponse();
        }

        [Rpc(0x30)]
        public async Task HandleNotifyAsync(NotifyRequest request)
        {
            await Task.Delay(10);
        }
    }
}";

        var result = RunGenerator(source);
        var generatedCode = result.GeneratedTrees.Single().ToString();
        
        return Verify(generatedCode)
            .UseDirectory("Snapshots")
            .ScrubLines(line => 
                line.Contains("// <auto-generated") ||
                line.Contains("#nullable"));
    }

    private GeneratorTestResult RunGenerator(string source)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(source);
        var references = AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => !a.IsDynamic && !string.IsNullOrWhiteSpace(a.Location))
            .Select(a => MetadataReference.CreateFromFile(a.Location))
            .ToList();

        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            new[] { syntaxTree, CSharpSyntaxTree.ParseText(ClientBaseCode) },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new FrameWork.NetWork.SourceGenerators.RpcSourceGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation);

        var result = driver.GetRunResult();
        return new GeneratorTestResult
        {
            Diagnostics = result.Diagnostics,
            GeneratedTrees = result.Results[0].GeneratedSources.Select(s => s.SyntaxTree).ToArray()
        };
    }

    private class GeneratorTestResult
    {
        public ImmutableArray<Diagnostic> Diagnostics { get; init; }
        public SyntaxTree[] GeneratedTrees { get; init; } = Array.Empty<SyntaxTree>();
    }
}
