namespace Tests.RpcSourceGenerator;

public static class VerifyHelper
{
    public static void Initialize()
    {
        // Configure Verify to scrub dynamic data
        VerifySourceGenerators.Initialize();
        
        // Scrub common dynamic lines
        VerifierSettings.ScrubLinesContaining("// <auto-generated");
        VerifierSettings.ScrubLinesContaining("#nullable");
    }
}
