<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <AppDesignerFolder>Properties</AppDesignerFolder>
        <RootNamespace>LobbyServer</RootNamespace>
        <AssemblyName>LobbyServer</AssemblyName>
    </PropertyGroup>
    <PropertyGroup>
        <ApplicationIcon>lobby.ico</ApplicationIcon>
    </PropertyGroup>
    <ItemGroup>
        <Protobuf Include="..\AccountMgr.proto" GrpcServices="Client"/>
    </ItemGroup>
    <ItemGroup>
        <None Include="app.config"/>
        <None Include="packages.config"/>
    </ItemGroup>
    <ItemGroup>
        <Content Include="lobby.ico"/>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Common\Common.csproj" />
      <ProjectReference Include="..\FrameWork\FrameWork.csproj" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Google.ProtocolBuffers" Version="2.4.1.555" />
      <PackageReference Include="Grpc.Net.Client" Version="2.71.0">
      </PackageReference>
      <PackageReference Include="Grpc.Tools" Version="2.72.0">
          <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>
</Project>