<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <OutputType>Library</OutputType>
        <RootNamespace>Common</RootNamespace>
        <AssemblyName>Common</AssemblyName>
    </PropertyGroup>
    <!--  <ItemGroup>-->
    <!--    <Reference Include="Castle.Core, Version=5.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc, processorArchitecture=MSIL">-->
    <!--      <HintPath>..\packages\Castle.Core.5.2.1\lib\net462\Castle.Core.dll</HintPath>-->
    <!--    </Reference>-->
    <!--    <Reference Include="FakeItEasy, Version=8.0.0.0, Culture=neutral, PublicKeyToken=eff28e2146d5fd2c, processorArchitecture=MSIL">-->
    <!--      <HintPath>..\packages\FakeItEasy.8.3.0\lib\net462\FakeItEasy.dll</HintPath>-->
    <!--    </Reference>-->
    <!--    <Reference Include="Google.ProtocolBuffers, Version=2.4.1.555, Culture=neutral, PublicKeyToken=55f7125234beb589, processorArchitecture=MSIL">-->
    <!--      <HintPath>..\packages\Google.ProtocolBuffers.2.4.1.555\lib\net40\Google.ProtocolBuffers.dll</HintPath>-->
    <!--    </Reference>-->
    <!--    <Reference Include="Google.ProtocolBuffers.Serialization, Version=2.4.1.555, Culture=neutral, PublicKeyToken=55f7125234beb589, processorArchitecture=MSIL">-->
    <!--      <HintPath>..\packages\Google.ProtocolBuffers.2.4.1.555\lib\net40\Google.ProtocolBuffers.Serialization.dll</HintPath>-->
    <!--    </Reference>-->
    <!--    <Reference Include="System" />-->
    <!--    <Reference Include="System.Configuration" />-->
    <!--    <Reference Include="System.Core">-->
    <!--      <RequiredTargetFramework>3.5</RequiredTargetFramework>-->
    <!--    </Reference>-->
    <!--    <Reference Include="System.Drawing" />-->
    <!--    <Reference Include="System.Windows.Forms" />-->
    <!--    <Reference Include="System.Xml.Linq">-->
    <!--      <RequiredTargetFramework>3.5</RequiredTargetFramework>-->
    <!--    </Reference>-->
    <!--    <Reference Include="System.Data.DataSetExtensions">-->
    <!--      <RequiredTargetFramework>3.5</RequiredTargetFramework>-->
    <!--    </Reference>-->
    <!--    <Reference Include="System.Data" />-->
    <!--    <Reference Include="System.Xml" />-->
    <!--    <Reference Include="xunit.abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c, processorArchitecture=MSIL">-->
    <!--      <HintPath>..\packages\xunit.abstractions.2.0.3\lib\net35\xunit.abstractions.dll</HintPath>-->
    <!--    </Reference>-->
    <!--    <Reference Include="xunit.core, Version=2.9.3.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c, processorArchitecture=MSIL">-->
    <!--      <HintPath>..\packages\xunit.extensibility.core.2.9.3\lib\net452\xunit.core.dll</HintPath>-->
    <!--    </Reference>-->
    <!--  </ItemGroup>-->
    <ItemGroup>
        <ProjectReference Include="..\FrameWork\FrameWork.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <Content Include="Icons\account.ico"/>
        <Content Include="Icons\launcher.ico"/>
        <Content Include="Icons\lobby.ico"/>
        <Content Include="Icons\world.ico"/>
    </ItemGroup>
    <ItemGroup>
        <None Include="app.config"/>
        <None Include="packages.config"/>
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Protos\"/>
    </ItemGroup>
</Project>