<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Library</OutputType>
        <RootNamespace>FrameWork</RootNamespace>
        <AssemblyName>FrameWork</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <None Include="app.config"/>
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="FastGenericNew.SourceGenerator" Version="3.3.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Google.Protobuf" Version="3.32.1">
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.2" />
      <PackageReference Include="MySql.Data" Version="9.4.0">
      </PackageReference>
      <PackageReference Include="NLog" Version="6.0.4" />  
      <PackageReference Include="System.Data.Odbc" Version="9.0.9">
      </PackageReference>
      <PackageReference Include="System.Data.OleDb" Version="9.0.9">
      </PackageReference>
      <PackageReference Include="System.Data.SqlClient" Version="4.9.0">
      </PackageReference>
      <PackageReference Include="System.Threading.Channels" Version="8.0.0" />
    </ItemGroup>
</Project>