namespace Core.Infrastructure.Network;

/// <summary>
/// Dispatches incoming packets to the appropriate handler methods.
/// Implementations are generated by the RpcSourceGenerator — one per packet group.
/// The dispatcher resolves handler instances from the connection-scoped service provider,
/// so handlers are cached per-connection via scoped DI lifetime.
/// </summary>
public interface IPacketDispatcher
{
    /// <summary>
    /// Dispatches a packet to the appropriate handler method.
    /// </summary>
    /// <param name="opcode">The packet opcode.</param>
    /// <param name="payload">The packet payload bytes (opcode already extracted).</param>
    /// <param name="services">The connection-scoped service provider for resolving handlers and [FromServices] parameters.</param>
    /// <param name="serializer">The packet serializer for deserializing request DTOs.</param>
    /// <param name="connection">The connection context passed to handlers that accept IConnectionContext.</param>
    void Dispatch(
        byte opcode,
        ReadOnlyMemory<byte> payload,
        IServiceProvider services,
        IPacketSerializer serializer,
        IConnectionContext connection);
}
