insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (0, ' BO Big Tick', 1, 4);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (1, ' BO Small Tick', 1, 12);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (2, ' BO Unlock Tick', 2, 4);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (3, ' Player Kill DB', 4, 15);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (4, ' Player Kill on BO', 2, 20);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (5, ' Kill Keep Lord', 8, 2);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (6, ' Destroy Outer Door', 2, 4);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (7, ' Destroy Inner Door', 3, 4);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (8, ' Destroy Siege', 1, 8);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (9, ' Player Kill Assist', 1, 30);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (10, ' Play Scenario', 4, 6);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (11, ' Win Scenario', 8, 6);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (12, ' Keep Defence Tick', 5, 2);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (13, ' Player Kill under AAO', 2, 20);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (14, ' Player Kill Assist under AAO', 1, 20);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (15, ' Warband Leader BO Big Tick', 3, 3);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (16, ' Warband Leader Kill Keep Lord', 5, 2);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (17, ' Resurrect Player', 2, 10);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (18, ' Out of group healing', 1, 15);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (19, ' Party Kill Assist', 1, 20);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (20, ' Realm Captain Kill', 8, 3);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (21, ' Player Kill Assist on BO', 1, 12);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (22, ' Punt Enemy', 1, 5);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (23, ' Hold the Line', 1, 5);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (24, ' Tank Guard', 1, 10);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (25, ' General Healing', 1, 30);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (26, ' Knockdown', 1, 5);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values (27, ' AOE Root', 1, 5);
insert into war_world.bounty_contribution_definition (ContributionId, ContributionDescription, ContributionValue, MaxContributionCount) values ( 28, ' Morale Root (ChCh)', 1, 5);
