DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '5');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '6');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '7');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '8');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '9');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '10');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '15');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '16');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '17');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '18');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '19');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '20');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '25');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '26');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '27');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '28');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '29');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '30');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '100');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '101');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '102');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '103');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '104');
DELETE FROM `war_world`.`player_keep_spawn` WHERE (`KeepId` = '105');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('5', '1413598', '845990', '10081');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('6', '1402315', '874059', '9426');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('7', '1405748', '928193', '12107');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('8', '1370580', '928148', '12036');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('9', '1395562', '978671', '7813');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('10', '1414294', '1012023', '6077');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('15', '1439714', '911820', '18797');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('16', '1432067', '944133', '16720');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('17', '1446130', '882317', '15768');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('18', '1444283', '830954', '14438');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('19', '1440647', '763036', '13363');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('20', '1447515', '796673', '14125');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('25', '1070388', '1639850', '5766');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('26', '1033036', '1643738', '7332');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('27', '987825', '1635986', '11661');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('28', '968879', '1636866', '8244');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('29', '886872', '1637441', '6316');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('30', '929686', '1637774', '8493');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('100', '1430891', '966827', '17478');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('101', '1429827', '740655', '16057');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('102', '1398503', '1040259', '10498');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('103', '1398664', '815989', '13779');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('104', '868026', '1635588', '10507');
INSERT INTO `war_world`.`player_keep_spawn` (`KeepId`, `DefenderKeepSafeX`, `DefenderKeepSafeY`, `DefenderKeepSafeZ`) VALUES ('105', '1095875', '1638329', '8976');
