-- Imports live event tasks

-- The Wild Hunt
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('1', '1', 'Locate the Fallen Hunters', 'the Fallen Hunters', '6');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('2', '1', 'Complete \'Render Unto Kurnous\' quest', 'Render Unto Kurnous', '1');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('3', '1', 'Kill 5 Sacred Stags', 'Sacred Stags', '5');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('4', '1', 'Target the White Stag', 'Target The Stag of Kurnous', '1');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('5', '1', 'Participate in any Elf Scenario', ' Elf Scenario\'s', '3');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('6', '1', 'Kill five Beast-Hexed players', 'Beast-Hexed players', '5');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('7', '1', 'Receive the Curse of Kurnous five times', 'Receive Beast-Hexed five times', '5');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('8', '1', 'Complete all tasks on the Master Huntsman page', 'Master Huntsman Page', '16');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('9', '1', 'Kill The Spirit of Kurnous', 'The Spirit of Kurnous', '1');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('10', '1', 'Uncover the Secret to Reaching Kurnous\' Lair', 'Reach Kurnous\' Lair', '1');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('11', '1', 'Complete all Wild Hunt tasks', 'Wild Hunt Tasks', '10');

-- The Witching Night
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('12', '2', 'Restless Spirits Slain', 'Restless Spirits', '50');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('13', '2', 'Withered Crones Slain', 'Withered Crones', '25');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('14', '2', 'Witching Lords Slain', 'Witching Lords', '10');

-- Heavy Metal
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('15', '3', 'Participate in the Reikland Factory Scenario', 'Reikland Factory', '1');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('16', '3', 'Complete 3 Stages of a Public Quest', 'Public Quest', '3');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('17', '3', 'Complete the Scouting Quest that begins in Reikland Factory Scenario', 'Scouting Quest', '1');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('18', '3', 'Visit the Herald in a Capital City', 'Herald', '1');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('19', '3', 'Find the Sand Castle in the Reikland Factory Scenario', 'Sand Castle', '1');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('20', '3', 'Visit a Capital City', 'Capital', '1');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('21', '3', 'Defeat 15 enemy players in open RvR', 'Enemy Players', '15');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('22', '3', 'Kill 10 Factory Chickens in the Reikland Factory Scenario.', 'Factory Chickens', '10');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('23', '3', 'Kill 20 Undead.', 'Undead', '20');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('24', '3', 'Detonate the Steam Tank Ammo in the Reikland Factory Scenario.', 'Steam Tank Ammo', '1');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('25', '3', 'Complete 5 Quests.', 'Quests', '5');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('26', '3', 'Throw 5 Gaffer\'s Gravybombs at enemy players in the Reikland Factory Scenario.', 'Gaffer\'s Gravybombs', '5');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('27', '3', 'Complete 3 Stages of a Public Quest.', 'Public Quest', '3');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('28', '3', 'Have your realm eat the Famous Factory Sandwich in the Reikland Factory Scenario.', 'Famous Factory Sandwich', '1');

-- Keg End
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('29', '4', 'Massive Ogres Tyrants Slain', 'Ogres Tyrants Slain', '20');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('30', '4', '/Boast or /Toast a member of every career', 'Boast or Toast', '24');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('31', '4', 'Drink from 3 steins within the pubs and feast halls of the capital cities', 'Drink from steins', '3');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('32', '4', '/Boast 20 different dead enemy players', 'Boast dead enemy players', '20');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('33', '4', 'Drink Dwarf Beer Kegs retrieved from Brew-Thirsty Ogres, Drunken Gnoblars, and Explosive Snotlings', 'Drink Dwarf Beer Kegs', '100');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('34', '4', 'Explosive Snotlings Slain', 'Snotlings', '50');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('35', '4', 'Brew-Thirsty Ogres Slain', 'Ogres', '50');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('36', '4', 'Drunken Gnoblar Slain', 'Gnoblar', '50');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('37', '4', 'Keg Caches Guzzled', 'Keg Caches', '50');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('38', '4', 'Launch 10 Common Fireworks', 'Common Fireworks', '10');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('39', '4', 'Launch 5 Impressive Fireworks', 'Impressive Fireworks', '5');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('40', '4', 'Launch 1 Magnificent Firework', 'Magnificent Firework', '1');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('41', '4', 'Defeat 20 Enemy Players', 'Enemy Players', '20');
REPLACE INTO `war_world`.`liveevent_task_infos` (`Entry`, `LiveEventId`, `Name`, `Description`, `TotalTasks`) VALUES ('42', '4', 'Complete all Keg End Tasks Title: Keg Slayer!', 'Complete all Keg End Tasks', '13');