DELETE FROM `zone_areas` WHERE (`ZoneId` = '152') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '153') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '154') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '155') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '156') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '160') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '160') and (`PieceId` = '2');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '160') and (`PieceId` = '3');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '163') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '164') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '165') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '166') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '169') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '173') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '176') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '177') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '179') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '195') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '196') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '241') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '242') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '243') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '244') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '260') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '50') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '60') and (`PieceId` = '1');
DELETE FROM `zone_areas` WHERE (`ZoneId` = '63') and (`PieceId` = '1');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('The Sewers of Altdorf: Wing 1 - Sewers 2', '152', '31', '0', '1', '0', '0', '647', '648');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('The Sewers of Altdorf: Wing 2 - Sewers 3', '153', '31', '0', '1', '0', '0', '645', '646');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Warpblade Tunnels 2', '154', '31', '0', '1', '0', '0', '643', '644');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Sacellum Dungeons: West Wing - Sacellum 2', '155', '31', '0', '1', '0', '0', '641', '642');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Sacellum Dungeons: East Wing -  Sacellum 3', '156', '31', '0', '1', '0', '0', '639', '640');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Bastion Stair', '160', '31', '0', '1', '129', '128', '194', '600', '605');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Path of Fury', '160', '31', '0', '2', '129', '128', '600', '605');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Trail of Carnage', '160', '31', '0', '3', '129', '128', '600', '605');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Bastion Stair - Thar''Ignan', '163', '31', '0', '1', '129', '128', '601', '606');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Bastion Stair - Lord Slaurith', '164', '31', '0', '1', '129', '128', '602', '607');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Bastion Stair - Kaarn the Vanquisher', '165', '31', '0', '1', '129', '128', '603', '608');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Bastion Stair - Skull Lord Var''Ithrok', '166', '31', '0', '1', '129', '128', '604', '609');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('The Sewers of Altdorf: Wing 3 - Sewers', '169', '31', '0', '1', '0', '0', '631', '632');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Sacellum Dungeons: South Wing - Sacellum', '173', '31', '0', '1', '0', '0', '633', '634');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Sigmar Crypts', '176', '31', '0', '1', '0', '0', '629', '630');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Warpblade Tunnels 1', '177', '31', '0', '1', '0', '0', '627', '628');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Tomb of the Vulture Lord', '179', '31', '0', '1', '0', '0', '255', '635', '636');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Bloodwrought Enclave', '195', '31', '0', '1', '0', '0', '626', '339');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Bilerot Burrow', '196', '31', '0', '1', '0', '0', '625', '340');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Tomb of the Stars', '241', '31', '0', '1', '0', '0', '619', '620');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Tomb of the Moon', '242', '31', '0', '1', '0', '0', '298', '618');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Tomb of the Sky', '243', '31', '0', '1', '0', '0', '621', '622');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Tomb of the Sun', '244', '31', '0', '1', '0', '0', '623', '624');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`) VALUES ('The Lost Vale', '260', '31', '0', '1', '0', '0', '195');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Hunters Vale', '50', '31', '0', '1', '0', '0', '7450', '341', '342');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`, `OrderRespawnId`, `DestroRespawnId`) VALUES ('Mount Gunbad', '60', '31', '0', '1', '64', '65', '193', '308', '321');
INSERT INTO `zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`) VALUES ('Mount Gunbad Lab', '63', '31', '0', '1', '64', '65');
