DELETE FROM `zone_infos` WHERE (`ZoneId` = '152');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '153');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '154');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '155');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '156');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '160');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '163');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '164');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '165');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '166');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '169');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '173');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '176');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '177');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '179');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '195');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '196');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '241');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '242');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '243');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '244');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '260');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '50');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '60');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '63');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '64');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '65');
DELETE FROM `zone_infos` WHERE (`ZoneId` = '66');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('152', 'The Sewers of Altdorf: Wing 1 - Sewers 2', '31', '40', '6', '2', '0', '152', '40', '40', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('153', 'The Sewers of Altdorf: Wing 2 - Sewers 3', '31', '40', '6', '2', '0', '153', '40', '40', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('154', 'Warpblade Tunnels 2', '40', '40', '6', '0', '0', '154', '40', '40', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('155', 'Sacellum Dungeons: West Wing - Sacellum 2', '12', '18', '6', '2', '0', '155', '40', '40', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('156', 'Sacellum Dungeons: East Wing -  Sacellum 3', '12', '18', '6', '2', '0', '156', '40', '40', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('160', 'Bastion Stair', '34', '40', '6', '4', '0', '160', '240', '240', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('163', 'Bastion Stair - Thar''Ignan', '32', '40', '6', '4', '0', '163', '240', '240', '2', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('164', 'Bastion Stair - Lord Slaurith', '32', '40', '6', '4', '0', '164', '240', '240', '2', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('165', 'Bastion Stair - Kaarn the Vanquisher', '32', '40', '6', '4', '0', '165', '240', '240', '2', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('166', 'Bastion Stair - Skull Lord Var''Ithrok', '32', '40', '6', '4', '0', '166', '240', '240', '2', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('169', 'The Sewers of Altdorf: Wing 3 - Sewers', '31', '40', '6', '2', '0', '169', '24', '120', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('173', 'Sacellum Dungeons: South Wing - Sacellum', '12', '18', '0', '2', '0', '173', '160', '340', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('176', 'Sigmar Crypts', '40', '40', '6', '4', '0', '176', '360', '48', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('177', 'Warpblade Tunnels 1', '40', '40', '6', '4', '0', '177', '376', '48', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('179', 'Tomb of the Vulture Lord - RvR Dungeon', '31', '40', '6', '4', '0', '179', '72', '60', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('195', 'Bloodwrought Enclave', '40', '40', '6', '4', '0', '195', '376', '248', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('196', 'Bilerot Burrow', '40', '40', '6', '4', '0', '196', '360', '248', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('241', 'Tomb of the Stars - RvR Lair 1', '32', '40', '6', '4', '0', '241', '72', '60', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('242', 'Tomb of the Moon - RvR Lair 2', '32', '40', '6', '4', '0', '242', '72', '60', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('243', 'Tomb of the Sky - RvR Lair 3', '32', '40', '6', '4', '0', '243', '72', '60', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('244', 'Tomb of the Sun - RvR Lair 4', '32', '40', '6', '4', '0', '244', '72', '60', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('260', 'Lost Vale', '32', '40', '6', '4', '0', '260', '336', '376', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('50', 'Hunter''s Vale', '1', '40', '4', '4', '0', '50', '72', '120', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('60', 'Mount Gunbad Realm 1', '22', '40', '4', '4', '0', '60', '200', '200', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('63', 'Gunbad Nursery', '22', '40', '6', '4', '0', '63', '216', '216', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('64', 'Gunbad Lab', '22', '40', '6', '4', '0', '64', '232', '232', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('65', 'Squig Boss', '22', '40', '6', '4', '0', '65', '300', '300', '0', '1', '0');
INSERT INTO `zone_infos` (`ZoneId`, `Name`, `MinLevel`, `MaxLevel`, `Type`, `Tier`, `Price`, `Region`, `OffX`, `OffY`, `Pairing`, `Collision`, `Illegal`) VALUES ('66', 'Gunbad Barracks', '22', '40', '6', '4', '0', '66', '264', '264', '0', '1', '0');
