DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '1');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '2');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '3');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '4');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '5');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '6');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '7');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '8');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '9');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '10');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '11');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '12');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '13');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '14');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '15');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '16');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '17');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '18');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '2', 'Chaos Wastes', '1', '15', '2', '11', '103', '2', '0', '2', '0', '0', '0', '19', '20');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '2', 'Praag', '2', '1', '3', '11', '105', '0', '1', '0', '1', '0', '0', '18', '17');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '2', 'Reikland', '3', '2', '13', '11', '109', '1', '0', '1', '0', '0', '0', '15', '16');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '1', 'Black Crag', '4', '16', '5', '2', '3', '2', '0', '2', '0', '0', '0', '10', '9');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '1', 'Thunder Mountain', '5', '4', '6', '2', '5', '0', '0', '0', '0', '0', '0', '7', '8');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '1', 'Kadrin Valley', '6', '5', '14', '2', '9', '1', '0', '1', '0', '0', '0', '6', '5');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '3', 'Eataine', '7', '8', '17', '4', '209', '1', '0', '1', '0', '0', '0', '26', '25');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '3', 'Dragonwake', '8', '9', '7', '4', '205', '0', '0', '0', '0', '0', '0', '28', '27');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '3', 'Caledor', '9', '18', '8', '4', '203', '2', '0', '2', '0', '0', '0', '29', '30');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('1', '2', 'Norsca / Nordland', '10', '11', '11', '8', '106', '0', '1', '0', '0', '0', '0', '0', '0');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('1', '1', 'Ekrund / Mt Bloodhorn', '11', '12', '12', '1', '6', '2', '0', '2', '1', '0', '0', '0', '0');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('1', '3', 'Chrace / Blighted Isle', '12', '10', '10', '3', '206', '1', '0', '1', '0', '0', '0', '0', '0');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '2', 'Reikwald', '13', '2', '2', '11', '110', '1', '0', '1', '0', '0', '0', '100', '100');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '1', 'Stonewatch', '14', '2', '2', '2', '10', '1', '0', '1', '0', '0', '0', '14', '14');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '2', 'The Maw', '15', '5', '5', '11', '104', '2', '0', '2', '0', '0', '0', '101', '101');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '1', 'Butchers Pass', '16', '2', '2', '2', '4', '2', '0', '2', '0', '0', '0', '102', '102');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '3', 'Shining Way', '17', '2', '2', '4', '210', '1', '0', '1', '0', '0', '0', '105', '105');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '3', 'Fell Landing', '18', '2', '2', '4', '204', '2', '0', '2', '0', '0', '0', '104', '104');


UPDATE `war_world`.`rvr_progression` SET `OrderWinProgression` = '5', `DestWinProgression` = '5' WHERE (`BattleFrontId` = '13');
UPDATE `war_world`.`rvr_progression` SET `OrderWinProgression` = '8', `DestWinProgression` = '8' WHERE (`BattleFrontId` = '14');
UPDATE `war_world`.`rvr_progression` SET `OrderWinProgression` = '8', `DestWinProgression` = '8' WHERE (`BattleFrontId` = '16');

UPDATE `war_world`.`rvr_progression` SET `DestroKeepId` = '103', `OrderKeepId` = '103' WHERE (`BattleFrontId` = '14');


