## Increasing hatred generated by tank hate genenerating ability
UPDATE `war_world`.`ability_damage_heals` SET `HatredScale` = '5' WHERE (`Entry` = '8315') and (`Index` = '0') and (`ParentCommandID` = '0') and (`ParentCommandSequence` = '0');
UPDATE `war_world`.`ability_damage_heals` SET `HatredScale` = '5' WHERE (`Entry` = '9315') and (`Index` = '0') and (`ParentCommandID` = '0') and (`ParentCommandSequence` = '0');
UPDATE `war_world`.`ability_damage_heals` SET `HatredScale` = '5' WHERE (`Entry` = '1355') and (`Index` = '0') and (`ParentCommandID` = '0') and (`ParentCommandSequence` = '0');
UPDATE `war_world`.`ability_damage_heals` SET `HatredScale` = '5' WHERE (`Entry` = '8002') and (`Index` = '0') and (`ParentCommandID` = '0') and (`ParentCommandSequence` = '0');
UPDATE `war_world`.`ability_damage_heals` SET `HatredScale` = '5' WHERE (`Entry` = '3831') and (`Index` = '1') and (`ParentCommandID` = '0') and (`ParentCommandSequence` = '0');
UPDATE `war_world`.`ability_damage_heals` SET `HatredScale` = '5' WHERE (`Entry` = '9002') and (`Index` = '0') and (`ParentCommandID` = '0') and (`ParentCommandSequence` = '0');
UPDATE `war_world`.`ability_damage_heals` SET `HatredScale` = '5' WHERE (`Entry` = '1664') and (`Index` = '0') and (`ParentCommandID` = '0') and (`ParentCommandSequence` = '0');
