INSERT INTO `war_world`.`buff_infos` (`Entry`, `Name`, `BuffClassString`, `MaxCopies`, `MaxStack`, `PersistsOnDeath`) VALUES ('10140', 'Anguish VIII', 'Career', '1', '1', '1');
INSERT INTO `war_world`.`buff_infos` (`Entry`, `Name`, `Group`, `MaxStack`, `Duration`, `Interval`, `Silent`) VALUES ('10565', 'Anguish VIII Proc', '30', '1', '9', '3000', '1');
INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `InvokeOn`, `Target`, `EffectRadius`, `EventIDString`, `EventChance`, `BuffLine`) VALUES ('10140', 'Anguish VIII', '0', '0', 'InvokeBuff', '10566', '0', 'EventInstigator', '0', 'DirectDamageDealt', '5', '1');
INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `InvokeOn`, `Target`, `BuffLine`) VALUES ('10565', 'Anguish VIII Proc', '0', '0', 'DamageOverTime', '7', 'Host', '1');
INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `InvokeOn`, `Target`, `BuffLine`) VALUES ('10565', 'Anguish VIII Proc', '1', '0', 'ModifySpeed', '-46', '5', 'Host', '2');
INSERT INTO `war_world`.`ability_damage_heals` (`Entry`, `Index`, `Name`, `MinDamage`, `MaxDamage`, `DamageType`, `ParentCommandID`, `ParentCommandSequence`, `NoCrits`, `HatredScale`, `HealHatredScale`) VALUES ('10565', '1', 'Anguish VIII Proc', '144', '144', 'Spiritual', '0', '0', '1', '1', '1');
UPDATE `war_world`.`item_infos` SET `Effects` = '10140' WHERE (`Entry` = '475091');
UPDATE `war_world`.`item_infos` SET `Effects` = '10128' WHERE (`Entry` = '475144');
INSERT INTO `war_world`.`buff_infos` (`Entry`, `Name`, `BuffClassString`, `MaxCopies`, `MaxStack`, `PersistsOnDeath`) VALUES ('10126', 'Chill VIII', 'Career', '1', '1', '1');
INSERT INTO `war_world`.`buff_infos` (`Entry`, `Name`, `Group`, `MaxStack`, `Duration`, `Interval`, `Silent`) VALUES ('10552', 'Chill VIII Proc', '30', '1', '9', '3000', '1');
INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `InvokeOn`, `Target`, `EffectRadius`, `EventIDString`, `EventChance`, `BuffLine`) VALUES ('10126', 'Chill VIII', '0', '0', 'InvokeBuff', '10552', '0', 'EventInstigator', '0', 'DirectDamageDealt', '5', '1');
INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `InvokeOn`, `Target`, `BuffLine`) VALUES ('10552', 'Chill VIII Proc', '0', '0', 'DamageOverTime', '7', 'Host', '1');
INSERT INTO `war_world`.`buff_commands` (`Entry`, `Name`, `CommandID`, `CommandSequence`, `CommandName`, `PrimaryValue`, `InvokeOn`, `Target`, `BuffLine`) VALUES ('10552', 'Chill VIII Proc', '1', '0', 'ModifySpeed', '-46', '5', 'Host', '2');
UPDATE `war_world`.`buff_commands` SET `Entry` = '10554' WHERE (`Entry` = '10552') and (`CommandID` = '0') and (`CommandSequence` = '0');
UPDATE `war_world`.`buff_commands` SET `Entry` = '10554' WHERE (`Entry` = '10552') and (`CommandID` = '1') and (`CommandSequence` = '0');
UPDATE `war_world`.`buff_commands` SET `Entry` = '10128', `PrimaryValue` = '10554' WHERE (`Entry` = '10126') and (`CommandID` = '0') and (`CommandSequence` = '0');
UPDATE `war_world`.`buff_infos` SET `Entry` = '10554' WHERE (`Entry` = '10552');
UPDATE `war_world`.`buff_infos` SET `Entry` = '10128' WHERE (`Entry` = '10126');
UPDATE `war_world`.`buff_commands` SET `PrimaryValue` = '10565' WHERE (`Entry` = '10140') and (`CommandID` = '0') and (`CommandSequence` = '0');
INSERT INTO `war_world`.`ability_damage_heals` (`Entry`, `Index`, `Name`, `MinDamage`, `MaxDamage`, `DamageType`, `ParentCommandID`, `ParentCommandSequence`, `NoCrits`, `HatredScale`, `HealHatredScale`) VALUES ('10554', '1', 'Chill VIII Proc', '146', '146', 'Elemental', '0', '0', '1', '1', '1');
UPDATE `war_world`.`item_infos` SET `Stats` = '9:78;0:0;33:3;78:5;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;' WHERE (`Entry` = '475144');
UPDATE `war_world`.`item_infos` SET `Stats` = '9:78;0:0;33:3;78:5;0:0;0:0;0:0;0:0;0:0;0:0;0:0;0:0;' WHERE (`Entry` = '475091');