DELETE FROM `war_world`.`zone_areas` WHERE (`ZoneId` = '4') and (`PieceId` = '1');
DELETE FROM `war_world`.`zone_areas` WHERE (`ZoneId` = '4') and (`PieceId` = '2');
DELETE FROM `war_world`.`zone_areas` WHERE (`ZoneId` = '4') and (`PieceId` = '30');
DELETE FROM `war_world`.`zone_areas` WHERE (`ZoneId` = '10') and (`PieceId` = '1');
DELETE FROM `war_world`.`zone_areas` WHERE (`ZoneId` = '10') and (`PieceId` = '2');
DELETE FROM `war_world`.`zone_areas` WHERE (`ZoneId` = '10') and (`PieceId` = '30');
DELETE FROM `war_world`.`zone_areas` WHERE (`ZoneId` = '104') and (`PieceId` = '1');
DELETE FROM `war_world`.`zone_areas` WHERE (`ZoneId` = '104') and (`PieceId` = '2');
DELETE FROM `war_world`.`zone_areas` WHERE (`ZoneId` = '104') and (`PieceId` = '30');
DELETE FROM `war_world`.`zone_areas` WHERE (`ZoneId` = '110') and (`PieceId` = '1');
DELETE FROM `war_world`.`zone_areas` WHERE (`ZoneId` = '204') and (`PieceId` = '1');
DELETE FROM `war_world`.`zone_areas` WHERE (`ZoneId` = '204') and (`PieceId` = '2');
DELETE FROM `war_world`.`zone_areas` WHERE (`ZoneId` = '204') and (`PieceId` = '30');
DELETE FROM `war_world`.`zone_areas` WHERE (`ZoneId` = '210') and (`PieceId` = '1');
DELETE FROM `war_world`.`zone_areas` WHERE (`ZoneId` = '210') and (`PieceId` = '2');
DELETE FROM `war_world`.`zone_areas` WHERE (`ZoneId` = '210') and (`PieceId` = '30');
INSERT INTO `war_world`.`zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`) VALUES ('Butcher\'s Pass', '4', '0', '0', '1', '169', '49', '5837');
INSERT INTO `war_world`.`zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`) VALUES ('Butcher\'s Pass', '4', '61', '2', '2', '169', '49', '5837');
INSERT INTO `war_world`.`zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`) VALUES ('Butcher\'s Pass', '4', '61', '0', '30', '58', '49', '5837');
INSERT INTO `war_world`.`zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`) VALUES ('Stonewatch', '10', '0', '0', '1', '169', '49', '5838');
INSERT INTO `war_world`.`zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`) VALUES ('Stonewatch', '10', '61', '1', '2', '169', '49', '5838');
INSERT INTO `war_world`.`zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`) VALUES ('Stonewatch', '10', '61', '0', '30', '58', '49', '5838');
INSERT INTO `war_world`.`zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`) VALUES ('The Maw', '104', '0', '0', '1', '42', '113', '5839');
INSERT INTO `war_world`.`zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`) VALUES ('The Maw', '104', '1', '2', '2', '42', '113', '5839');
INSERT INTO `war_world`.`zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`) VALUES ('The Maw', '104', '1', '0', '30', '122', '113', '5839');
INSERT INTO `war_world`.`zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`) VALUES ('Reikwald', '110', '30', '0', '1', '122', '113', '5840');
INSERT INTO `war_world`.`zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`) VALUES ('Fell Landing', '204', '0', '0', '1', '186', '177', '5841');
INSERT INTO `war_world`.`zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`) VALUES ('Fell Landing', '204', '61', '2', '2', '186', '177', '5841');
INSERT INTO `war_world`.`zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`) VALUES ('Fell Landing', '204', '61', '0', '30', '186', '177', '5841');
INSERT INTO `war_world`.`zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`) VALUES ('Shining Way', '210', '0', '0', '1', '186', '177', '5842');
INSERT INTO `war_world`.`zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`) VALUES ('Shining Way', '210', '61', '1', '2', '186', '177', '5842');
INSERT INTO `war_world`.`zone_areas` (`AreaName`, `ZoneId`, `AreaId`, `Realm`, `PieceId`, `OrderInfluenceId`, `DestroInfluenceId`, `TokExploreEntry`) VALUES ('Shining Way', '210', '61', '0', '30', '186', '177', '5842');
