<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Library</OutputType>
        <RootNamespace>Common</RootNamespace>
        <AssemblyName>Common</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\FrameWork\FrameWork.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <Content Include="Icons\account.ico"/>
        <Content Include="Icons\launcher.ico"/>
        <Content Include="Icons\lobby.ico"/>
        <Content Include="Icons\world.ico"/>
    </ItemGroup>
    <ItemGroup>
        <None Include="app.config"/>
        <None Include="packages.config"/>
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Protos\"/>
    </ItemGroup>
</Project>