DELETE FROM `war_world`.`liveevent_reward_infos`

/*
-- The Witching Night
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('1', '2', '1', '189841');
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('2', '2', '2', '0');
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('3', '2', '3', '206603');
*/

/*
-- The Wild Hunt
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('1', '1', '1', '207601');
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('2', '1', '2', '207602');
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('3', '1', '3', '0');
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('4', '1', '3', '0');
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('5', '1', '3', '0');
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('6', '1', '3', '0');
*/

/*
-- Keg End
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('1', '4', '1', '7190');
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('2', '4', '2', '129838731');
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('3', '4', '4', '206655');
*/

/*
-- Heavy Metal
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('1', '3', '1', '206608');
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('2', '3', '2', '640480');
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('3', '3', '2', '640481');
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('4', '3', '2', '640482');
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('5', '3', '2', '640483');
INSERT INTO `war_world`.`liveevent_reward_infos` (`Entry`, `LiveEventId`, `RewardGroupId`, `ItemId`) VALUES ('6', '3', '3', '206613');
*/