<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>AccountCacher</RootNamespace>
        <AssemblyName>AccountCacher</AssemblyName>
        <ApplicationIcon>account.ico</ApplicationIcon>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="..\..\protos\common\**\*.proto" ProtoRoot="..\..\protos" />
        <Protobuf Include="..\..\protos\AccountMgr.proto" GrpcServices="Server" ProtoRoot="..\..\protos" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="account.ico"/>
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Common\Common.csproj"/>
        <ProjectReference Include="..\FrameWork\FrameWork.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    </ItemGroup>

</Project>